### ISSUE TITLE
[Bug]: One component's integ test failure leads to whole integ test fail to continue

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-build#1159]
### Describe the bug

When running integ test `./test.sh integ-test .`, the component alerting has failed integ tests. But the termination logic throws exceptions which leads the whole command to stop.

```
2021-11-25 08:31:43 INFO     200: {"cluster_name":"opensearch","status":"green","timed_out":false,"number_of_nodes":1,"number_of_data_nodes":1,"discovered_master":true,"active_primary_shards":1,"active_shards":1,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":0,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":100.0}
2021-11-25 08:31:43 INFO     Service is available
2021-11-25 08:31:43 INFO     ===============================================
2021-11-25 08:31:43 INFO     Running integration tests for alerting
2021-11-25 08:31:43 INFO     ===============================================
2021-11-25 08:31:43 INFO     Executing "/usr/share/opensearch/workspace/opensearch-build/scripts/components/alerting/integtest.sh -b localhost -p 9200 -s true -v 1.2.0" in /tmp/tmp7ylgdaf9/alerting
2021-11-25 08:34:46 INFO     Recording component test results for alerting at /usr/share/opensearch/workspace/opensearch-build/test-results/29465f14e581428e91ef7eb32306db19/integ-test/alerting/with-security/test-results
2021-11-25 08:34:46 INFO     Walking tree from /tmp/tmp7ylgdaf9/alerting/build/reports/tests/integTest
2021-11-25 08:34:46 INFO     Integration test run failed for component alerting
2021-11-25 08:34:46 INFO     WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jetbrains.kotlin.com.intellij.util.ReflectionUtil (file:/usr/share/opensearch/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-embeddable/1.4.31/6451ea797cef544e81f507b0d9959cd97ae09c0/kotlin-compiler-embeddable-1.4.31.jar) to method java.util.ResourceBundle.setParent(java.util.ResourceBundle)
WARNING: Please consider reporting this to the maintainers of org.jetbrains.kotlin.com.intellij.util.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Note: /tmp/tmp7ylgdaf9/alerting/notification/src/main/java/org/opensearch/alerting/destination/Notification.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

2021-11-25 08:34:46 INFO     Sending SIGKILL to PID 1287930
2021-11-25 08:34:46 INFO     Process killed with exit code None
2021-11-25 08:34:46 INFO     Recording local cluster logs for alerting with test configuration as with-security at /usr/share/opensearch/workspace/opensearch-build/test-results/29465f14e581428e91ef7eb32306db19/integ-test/alerting/with-security/local-cluster-logs
Traceback (most recent call last):
  File "./src/run_integ_test.py", line 65, in <module>
    sys.exit(main())
  File "./src/run_integ_test.py", line 51, in main
    test_results = test_suite.execute()
  File "/usr/share/opensearch/workspace/opensearch-build/src/test_workflow/integ_test/integ_test_suite.py", line 57, in execute
    status = self.__setup_cluster_and_execute_test_config(config)
  File "/usr/share/opensearch/workspace/opensearch-build/src/test_workflow/integ_test/integ_test_suite.py", line 100, in __setup_cluster_and_execute_test_config
    return self.__execute_integtest_sh(test_cluster_endpoint, test_cluster_port, security, config)
  File "/usr/local/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/usr/share/opensearch/workspace/opensearch-build/src/test_workflow/test_cluster.py", line 28, in create
    cluster.destroy()
  File "/usr/share/opensearch/workspace/opensearch-build/src/test_workflow/integ_test/local_test_cluster.py", line 65, in destroy
    self.service_opensearch.terminate()
  File "/usr/share/opensearch/workspace/opensearch-build/src/test_workflow/integ_test/service.py", line 38, in terminate
    self.__test_result_data()
  File "/usr/share/opensearch/workspace/opensearch-build/src/test_workflow/integ_test/service.py", line 45, in __test_result_data
    self.save_logs.save_test_result_data(test_result_data)
  File "/usr/share/opensearch/workspace/opensearch-build/src/test_workflow/test_recorder/test_recorder.py", line 71, in save_test_result_data
    shutil.copyfile(log_file[0], dest_file)
  File "/usr/local/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
IsADirectoryError: [Errno 21] Is a directory: '/tmp/tmp7ylgdaf9/local-test-cluster/opensearch-1.2.0/logs'

```

### To reproduce

check out the build repo `main` branch (my head commit is `c0490fb7a5cdc8eca7c73a48f19a4ca10b1be2d8`)

Run build and then assemble.

Then run `./test.sh integ-test .`

**Comment by tianleh** [comment]
I plan to add some validation before the call `shutil.copyfile(log_file[0], dest_file)` so that the exception will throw.

`IsADirectoryError: [Errno 21] Is a directory: '/tmp/tmp7ylgdaf9/local-test-cluster/opensearch-1.2.0/logs'`


@dblock @seraphjiang

**Comment by tianleh** [comment]
Need to properly read the structure of the output. PR sent.

**Comment by dblock** [comment]
The issue that one failure aborts all other integration tests seems like something we do want to address.
