### ISSUE TITLE
Build workflow force patch versions plugins zips to have the same version as the patch version

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#1225]
### Describe the bug

In https://github.com/opensearch-project/opensearch-build/issues/373 patch release is successfully added so I test it with OpenSearch-Dashboards 1.1.1 by manually creating a folder on S3 and add all the 1.1.0 zips, with the same structure as needed.

The artifacts are downloaded successfully but seems like it is still trying to match the upcoming dashboards version 1.1.1 to the plugin zips name which has 1.1.0.

https://github.com/opensearch-project/opensearch-build/blob/60345d6794104ce71cd42c[…]d_workflow/opensearch_dashboards/build_artifact_check_plugin.py

```

$ ./build.sh manifests/1.1.1/opensearch-dashboards-1.1.1.yml --platform linux
Installing dependencies in . ...
Installing dependencies from Pipfile.lock (c3492c)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Running ./src/run_build.py manifests/1.1.1/opensearch-dashboards-1.1.1.yml --platform linux ...
2021-12-01 17:08:54 INFO     Building in /var/folders/d6/19_cf3qd6jb715ckzv_2jsvdmr559j/T/tmpsqjq68ai
2021-12-01 17:08:54 INFO     Building OpenSearch Dashboards (x64) into /Users/zhujiaxi/amazonworks/sourcecodes/peterzhuamazon/opensearch-build/builds/opensearch-dashboards
2021-12-01 17:08:54 INFO     Building OpenSearch-Dashboards
2021-12-01 17:08:54 INFO     Downloading https://ci.opensearch.org/ci/dbc/bundle-build-dashboards/1.1.0/20210930/linux/x64/builds/opensearch-dashboards/manifest.yml ...
2021-12-01 17:08:54 INFO     Loading https://ci.opensearch.org/ci/dbc/bundle-build-dashboards/1.1.0/20210930/linux/x64/builds/opensearch-dashboards/manifest.yml
2021-12-01 17:08:55 INFO     Downloading OpenSearch-Dashboards 1.1.0.0 (44d2cb5b4f9a7c641c1fef32ec569bc48ec46979) ...
2021-12-01 17:08:55 INFO     Distribution was built from https://github.com/opensearch-project/OpenSearch-Dashboards.git#1.1
2021-12-01 17:08:55 INFO     Downloading into builds/dist ...
2021-12-01 17:08:55 INFO     Downloading https://ci.opensearch.org/ci/dbc/bundle-build-dashboards/1.1.0/20210930/linux/x64/builds/opensearch-dashboards/dist/opensearch-dashboards-min-1.1.0-linux-x64.tar.gz into /private/var/folders/d6/19_cf3qd6jb715ckzv_2jsvdmr559j/T/tmpsqjq68ai/builds/dist/opensearch-dashboards-min-1.1.0-linux-x64.tar.gz
2021-12-01 17:09:04 INFO     Recording dist artifact for OpenSearch-Dashboards: dist/opensearch-dashboards-min-1.1.0-linux-x64.tar.gz (from /private/var/folders/d6/19_cf3qd6jb715ckzv_2jsvdmr559j/T/tmpsqjq68ai/builds/dist/opensearch-dashboards-min-1.1.0-linux-x64.tar.gz)
2021-12-01 17:09:04 INFO     Building alertingDashboards
2021-12-01 17:09:04 INFO     Downloading https://ci.opensearch.org/ci/dbc/bundle-build-dashboards/1.1.0/20210930/linux/x64/builds/opensearch-dashboards/manifest.yml ...
2021-12-01 17:09:04 INFO     Loading https://ci.opensearch.org/ci/dbc/bundle-build-dashboards/1.1.0/20210930/linux/x64/builds/opensearch-dashboards/manifest.yml
2021-12-01 17:09:04 INFO     Downloading alertingDashboards 1.1.0.0 (ff9edaab1c7baf9c72192d9e8c6965886ce80b24) ...
2021-12-01 17:09:04 INFO     Distribution was built from https://github.com/opensearch-project/alerting-dashboards-plugin#1.1
2021-12-01 17:09:04 INFO     Downloading into builds/plugins ...
2021-12-01 17:09:04 INFO     Downloading https://ci.opensearch.org/ci/dbc/bundle-build-dashboards/1.1.0/20210930/linux/x64/builds/opensearch-dashboards/plugins/alertingDashboards-1.1.0.zip into /private/var/folders/d6/19_cf3qd6jb715ckzv_2jsvdmr559j/T/tmpsqjq68ai/builds/plugins/alertingDashboards-1.1.0.zip
2021-12-01 17:09:06 INFO     Recording plugins artifact for alertingDashboards: plugins/alertingDashboards-1.1.0.zip (from /private/var/folders/d6/19_cf3qd6jb715ckzv_2jsvdmr559j/T/tmpsqjq68ai/builds/plugins/alertingDashboards-1.1.0.zip)
2021-12-01 17:09:06 ERROR    Error building alertingDashboards, retry with: ./build.sh manifests/1.1.1/opensearch-dashboards-1.1.1.yml --component alertingDashboards
Traceback (most recent call last):
  File "./src/run_build.py", line 83, in <module>
    sys.exit(main())
  File "./src/run_build.py", line 72, in main
    builder.export_artifacts(build_recorder)
  File "./src/build_workflow/builder_from_dist.py", line 46, in export_artifacts
    build_recorder.record_artifact(self.component.name, artifact_type, artifact, artifact_dest)
  File "./src/build_workflow/build_recorder.py", line 37, in record_artifact
    BuildArtifactChecks.check(self.target, artifact_type, artifact_file)
  File "./src/build_workflow/build_artifact_checks.py", line 39, in check
    instance.check(path)
  File "./src/build_workflow/opensearch_dashboards/build_artifact_check_plugin.py", line 25, in check
    f"Expected filename to be in the format of pluginName-{opensearch_dashboards_version}.zip.",
build_workflow.build_artifact_check.BuildArtifactInvalidError: Artifact alertingDashboards-1.1.0.zip is invalid. Expected filename to be in the format of pluginName-1.1.1.zip.
```

This makes a patch version not possible to be produced due to version match cannot be skipped.

Thanks.

### To reproduce

Git clone https://github.com/peterzhuamazon/opensearch-build/
Then checkout `opensearch-release-issues`.

Run `$ ./build.sh manifests/1.1.1/opensearch-dashboards-1.1.1.yml --platform linux`.

**Comment by peterzhuamazon** [comment]
Hi @dblock would be great if you can take a look.
Thanks.

**Comment by peterzhuamazon** [comment]
With @dblock suggestion I comment out `BuildArtifactOpenSearchDashboardsCheckPlugin#check`

```
+ PLUGIN_NAME=reportsDashboards
+ cp -r ../dashboards-reports/ ../../OpenSearch-Dashboards/plugins
cp: ../../OpenSearch-Dashboards/plugins: No such file or directory
cp: ../dashboards-reports/: unable to copy extended attributes to ../../OpenSearch-Dashboards/plugins: No such file or directory
cp: ../../OpenSearch-Dashboards/plugins/opensearch_dashboards.json: No such file or directory
cp: ../../OpenSearch-Dashboards/plugins/.cypress: No such file or directory
cp: ../dashboards-reports//.cypress: unable to copy extended attributes to ../../OpenSearch-Dashboards/plugins/.cypress: No such file or directory
cp: ../../OpenSearch-Dashboards/plugins/.cypress/plugins: No such file or directory
cp: ../dashboards-reports//.cypress/plugins: unable to copy extended attributes to ../../OpenSearch-Dashboards/plugins/.cypress/plugins: No such file or directory
cp: ../../OpenSearch-Dashboards/plugins/.cypress/plugins/index.js: No such file or directory
```

This happens when it reaches reports dashboards which I choose to build from source due to it is the one with changes.

And seems like it is complaining the OpenSearch-Dashboards/plugins does not exist.

Seems like it has a dependency of OpenSearch-Dashboards to build from source

**Comment by peterzhuamazon** [comment]
Suggested by DB I will get a working build script for reports, or just upload reports artifacts like other 1.1.0 plugins.

**Comment by dblock** [comment]
> Seems like it has a dependency of OpenSearch-Dashboards to build from source

Right, I remember that. So which version of OpenSearch Dashboards is reporting supposed to be building against when doing a patch? Sounds like 1.1.0 so include OpenSearch Dashboards in the manifest from the 1.1.0 tag instead of from dist.

**Comment by peterzhuamazon** [comment]
> > Seems like it has a dependency of OpenSearch-Dashboards to build from source
> 
> Right, I remember that. So which version of OpenSearch Dashboards is reporting supposed to be building against when doing a patch? Sounds like 1.1.0 so include OpenSearch Dashboards in the manifest from the 1.1.0 tag instead of from dist.

But we dont want to rebuild min from source.

**Comment by dblock** [comment]
> > > Seems like it has a dependency of OpenSearch-Dashboards to build from source
> > 
> > 
> > Right, I remember that. So which version of OpenSearch Dashboards is reporting supposed to be building against when doing a patch? Sounds like 1.1.0 so include OpenSearch Dashboards in the manifest from the 1.1.0 tag instead of from dist.
> 
> But we dont want to rebuild min from source.

I guess to have both means that a component that requires OpenSearch Dashboards to be built from source checks it out, builds it, uses it for its build independently. It's fine for a workaround, but it potentially introduces regressions, the dependency should really be on published artifacts, not source code.

I think @kavilla is the SME here to figure out what we should be doing for 1.1.1.
