### ISSUE TITLE
[Bug]Jenkins Opensearch is building snapshot that will fail on a patch release

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#1279]
### Describe the bug

There seems like an issue with the jenkins due to it is also running `--snapshot`

```
2021-12-09 18:55:45 ERROR    Error building job-scheduler, retry with: ./build.sh manifests/1.1.1/opensearch-1.1.1.yml --component job-scheduler --snapshot
Traceback (most recent call last):
  File "/var/jenkins/workspace/bundle-build@2/src/build_workflow/opensearch/build_artifact_check_maven.py", line 40, in check
    properties.check_value_in("Implementation-Version", versions)
  File "/var/jenkins/workspace/bundle-build@2/src/system/properties_file.py", line 55, in check_value_in
    raise PropertiesFile.UnexpectedKeyValuesError(key, expected, value)
system.properties_file.UnexpectedKeyValuesError: Expected to have Implementation-Version=any of [None, '1.1.1.0-SNAPSHOT', '1.1.0.0-SNAPSHOT', '1.1.1-SNAPSHOT', '1.1.0-SNAPSHOT'], but was '1.1.0.0'.

```

We are trying to release 1.1.1 based on 1.1.0 core, and the `--snapshot` is trying to build on non-exist `1.1.1` core.

Thanks.

### To reproduce

./build.sh manifests/1.1.1/opensearch-1.1.1.yml --component job-scheduler --snapshot

### Expected behavior

snapshot is disabled for patch releases, or it is building based on the patch core version.

**Comment by zelinh** [comment]
[Triage] @peterzhuamazon Could you please update the progress here.

**Comment by dblock** [comment]
I'm fixing this.

**Comment by peterzhuamazon** [comment]
```

total 8
drwxr-xr-x   3 zhujiaxi  staff    96 Dec  9 17:09 dist
drwxr-xr-x   3 zhujiaxi  staff    96 Dec  9 17:10 libs
-rw-r--r--   1 zhujiaxi  staff  3853 Dec  9 17:10 manifest.yml
drwxr-xr-x  14 zhujiaxi  staff   448 Dec  9 17:10 plugins

```

**Comment by dblock** [comment]
Fixed in https://github.com/opensearch-project/opensearch-build/pull/1281
