### ISSUE TITLE
CI checks for 1.2.0 are broken

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#1303]
Found in https://github.com/opensearch-project/opensearch-build/pull/1299

```
2021-12-11 04:11:23 INFO     Executing "./gradlew properties -Dopensearch.version=1.2.0-SNAPSHOT -Dbuild.snapshot=true" in /tmp/tmppugiofxn/cross-cluster-replication
2021-12-11 04:11:28 ERROR    CI Manifest check failed
Traceback (most recent call last):
  File "./src/run_ci.py", line 25, in <module>
    sys.exit(main())
  File "./src/run_ci.py", line 21, in main
    CiManifests.from_file(args.manifest, args).check()
  File "/home/runner/work/opensearch-build/opensearch-build/src/ci_workflow/ci_manifest.py", line 18, in check
    self.__check__()
  File "/home/runner/work/opensearch-build/opensearch-build/src/ci_workflow/ci_input_manifest.py", line 34, in __check__
    ci_check_list.check()
  File "/home/runner/work/opensearch-build/opensearch-build/src/ci_workflow/ci_check_list_source.py", line 41, in check
    instance.check()
  File "/home/runner/work/opensearch-build/opensearch-build/src/ci_workflow/ci_check_gradle_properties_version.py", line 21, in check
    self.properties.check_value("version", self.checked_version)
  File "/home/runner/work/opensearch-build/opensearch-build/src/system/properties_file.py", line 47, in check_value
    raise PropertiesFile.UnexpectedKeyValueError(key, expected, value)
system.properties_file.UnexpectedKeyValueError: Expected to have version='1.2.0.0-SNAPSHOT', but was '1.2.1.0-SNAPSHOT'.
```

We need to update the 1.2.0 manifest to use refs that point to before the latest change on the 1.2 branches since they were reused.  This also is something that we should have aprocess for after a build is release to prevent follow up work like this again, might be doable in one go to fix this release, or something that should be pulled out into another issue.

**Comment by dblock** [comment]
We should update those refs to tags and we have that in the process, don't we?

**Comment by dblock** [comment]
Fixed in https://github.com/opensearch-project/opensearch-build/pull/1307
