### ISSUE TITLE
[Bug]: security plugin failed the 1.2.0 OpenSearch build

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-build#1306]
### Describe the bug

```
./build.sh manifests/1.2.0/opensearch-1.2.0.yml
```
It failed at this step

```
2021-12-11 11:54:01 INFO     Recording plugins artifact for security: plugins/opensearch-security-1.2.1.0.zip (from /tmp/tmp1uh75bfd/security/builds/plugins/opensearch-security-1.2.1.0.zip)
2021-12-11 11:54:01 ERROR    Error building security, retry with: ./build.sh manifests/1.2.0/opensearch-1.2.0.yml --component security
Traceback (most recent call last):
  File "./src/run_build.py", line 78, in <module>
    sys.exit(main())
  File "./src/run_build.py", line 67, in main
    builder.export_artifacts(build_recorder)
  File "/usr/share/opensearch/workspace/opensearch-build/src/build_workflow/builder_from_source.py", line 59, in export_artifacts
    build_recorder.record_artifact(self.component.name, artifact_type, relative_path, absolute_path)
  File "/usr/share/opensearch/workspace/opensearch-build/src/build_workflow/build_recorder.py", line 37, in record_artifact
    BuildArtifactChecks.check(self.target, artifact_type, artifact_file)
  File "/usr/share/opensearch/workspace/opensearch-build/src/build_workflow/build_artifact_checks.py", line 39, in check
    instance.check(path)
  File "/usr/share/opensearch/workspace/opensearch-build/src/build_workflow/opensearch/build_artifact_check_plugin.py", line 20, in check
    raise BuildArtifactCheck.BuildArtifactInvalidError(path, f"Expected filename to include one of {self.target.compatible_component_versions}.")
build_workflow.build_artifact_check.BuildArtifactInvalidError: Artifact opensearch-security-1.2.1.0.zip is invalid. Expected filename to include one of ['1.2.0.0'].

```

### To reproduce

```
./build.sh manifests/1.2.0/opensearch-1.2.0.yml
```

**Comment by tianleh** [comment]
Error is gone after building with this https://github.com/opensearch-project/opensearch-build/pull/1307
