### ISSUE TITLE
[Bug]: Cannot Install any plugins on Opensearch Dockerfile

### ISSUE THREAD

**Issue by SiHaoShen** [opensearch-project/opensearch-build#1393]
### Describe the bug

Yesterday I could still install the plugins and build the docker image from the Dockerfile. But now it throws following errors.

I also tried with other Opensearch version such as 1.1.0, the problem still persists. 

And I cannot even install the plugin from
`wget https://artifacts.opensearch.org/releases/plugins/repository-s3/1.1.0/repository-s3-1.1.0.zip `

```
RUN bin/opensearch-plugin install -b discovery-ec2 && bin/opensearch-plugin install -b repository-s3 && sed -e '/^-Xm/s/^/#/g' -i /usr/share/opensearch/config/jvm.options
 ---> Running in 0305ee108a1e
-> Installing discovery-ec2
-> Failed installing discovery-ec2
-> Rolling back discovery-ec2
-> Rolled back discovery-ec2
Exception in thread "main" java.net.UnknownHostException: artifacts.opensearch.org
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:290)
	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1194)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1082)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142)
	at org.opensearch.plugins.InstallPluginCommand.urlExists(InstallPluginCommand.java:408)
	at org.opensearch.plugins.InstallPluginCommand.getOpenSearchUrl(InstallPluginCommand.java:375)
	at org.opensearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:297)
	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:260)
	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:237)
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
	at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
	at org.opensearch.cli.Command.main(Command.java:101)
	at org.opensearch.plugins.PluginCli.main(PluginCli.java:60)
The command '/bin/sh -c bin/opensearch-plugin install -b discovery-ec2 && bin/opensearch-plugin install -b repository-s3 && sed -e '/^-Xm/s/^/#/g' -i /usr/share/opensearch/config/jvm.options' returned a non-zero code: 1

```

### To reproduce

Run the following Dockerfile

```
FROM opensearchproject/opensearch:1.2.2

RUN bin/opensearch-plugin install -b discovery-ec2
```

### Expected behavior

Finish build the docker image successfully

### Screenshots

None

### Host / Environment

Ubuntu 20.04
Opensearch Version 1.2.2

**Comment by dblock** [comment]
Could it be transient, `wget https://artifacts.opensearch.org/releases/plugins/repository-s3/1.1.0/repository-s3-1.1.0.zip` works for me.

**Comment by bbarani** [comment]
Hi @SiHaoShen I couldn't replicate this issue. I am able to download the artifacts without any issues. Can you please check again and confirm?

 ```
wget https://artifacts.opensearch.org/releases/plugins/repository-s3/1.1.0/repository-s3-1.1.0.zip
--2021-12-21 16:20:52--  https://artifacts.opensearch.org/releases/plugins/repository-s3/1.1.0/repository-s3-1.1.0.zip
Resolving artifacts.opensearch.org (artifacts.opensearch.org)... 52.84.158.20, 52.84.158.122, 52.84.158.55, ...
Connecting to artifacts.opensearch.org (artifacts.opensearch.org)|52.84.158.20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4786819 (4.6M) [application/zip]
Saving to: ‘repository-s3-1.1.0.zip’

repository-s3-1.1.0.zip            100%[================================================================>]   4.56M  9.66MB/s    in 0.5s    
```

2021-12-21 16:20:53 (9.66 MB/s) - ‘repository-s3-1.1.0.zip’ saved [4786819/4786819]

**Comment by SiHaoShen** [comment]
Thank you for the help. I checked it again and it can be built successfully. Cheers!
