### ISSUE TITLE
[Bug]: 1.3.0 Opensearch staging Docker image fails to come up with security error

### ISSUE THREAD

**Issue by qreshi** [opensearch-project/opensearch-build#1445]
### Describe the bug

The [1.3.0 staging image for OpenSearch Docker](https://hub.docker.com/layers/opensearchstaging/opensearch/1.3.0/images/sha256-b4c8cad8423c7a7fd07c5a23ac3b8b5ae963b4012a2eed60df9263653e18dc61?context=explore) is failing to bring up a container when being used with the following exception:

```
Enabling execution of install_demo_configuration.sh for OpenSearch Security Plugin

OpenSearch Security Demo Installer

 ** Warning: Do not use on production or public reachable systems **

Basedir: /usr/share/opensearch

OpenSearch install type: rpm/deb on NAME="Amazon Linux"

OpenSearch config dir: /usr/share/opensearch/config

OpenSearch config file: /usr/share/opensearch/config/opensearch.yml

OpenSearch bin dir: /usr/share/opensearch/bin

OpenSearch plugins dir: /usr/share/opensearch/plugins

OpenSearch lib dir: /usr/share/opensearch/lib

Detected OpenSearch Version: x-content-1.3.0

Detected OpenSearch Security Version: 1.3.0.0


### Success

### Execute this script now on all your nodes and then start all nodes

### OpenSearch Security will be automatically initialized.

### If you like to change the runtime configuration 

### change the files in ../securityconfig and execute: 

"/usr/share/opensearch/plugins/opensearch-security/tools/securityadmin.sh" -cd "/usr/share/opensearch/plugins/opensearch-security/securityconfig" -icl -key "/usr/share/opensearch/config/kirk-key.pem" -cert "/usr/share/opensearch/config/kirk.pem" -cacert "/usr/share/opensearch/config/root-ca.pem" -nhnv

### or run ./securityadmin_demo.sh

### To use the Security Plugin ConfigurationGUI

### To access your secured cluster open https://<hostname>:<HTTP port> and log in with admin/admin.

### (Ignore the SSL certificate warning because we installed self-signed demo certificates)

Enabling OpenSearch Security Plugin

[2022-01-11T00:53:03,071][INFO ][o.o.n.Node               ] [5c871be79cf3] version[1.3.0], pid[106], build[tar/3f2831160c915479fc52d806186ce330bbf0edb9/2022-01-10T17:31:02.991436Z], OS[Linux/5.10.76-linuxkit/amd64], JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/15.0.1/15.0.1+9]

[2022-01-11T00:53:03,076][INFO ][o.o.n.Node               ] [5c871be79cf3] JVM home [/usr/share/opensearch/jdk], using bundled JDK [true]

[2022-01-11T00:53:03,076][INFO ][o.o.n.Node               ] [5c871be79cf3] JVM arguments [-Xshare:auto, -Dopensearch.networkaddress.cache.ttl=60, -Dopensearch.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -XX:+ShowCodeDetailsInExceptionMessages, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.locale.providers=SPI,COMPAT, -Xms1g, -Xmx1g, -XX:+UseG1GC, -XX:G1ReservePercent=25, -XX:InitiatingHeapOccupancyPercent=30, -Djava.io.tmpdir=/tmp/opensearch-13887360302178601300, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Dclk.tck=100, -Djdk.attach.allowAttachSelf=true, -Djava.security.policy=/usr/share/opensearch/plugins/opensearch-performance-analyzer/pa_config/opensearch_security.policy, -Dopensearch.cgroups.hierarchy.override=/, -XX:MaxDirectMemorySize=536870912, -Dopensearch.path.home=/usr/share/opensearch, -Dopensearch.path.conf=/usr/share/opensearch/config, -Dopensearch.distribution.type=tar, -Dopensearch.bundled_jdk=true]

[2022-01-11T00:53:05,476][WARN ][stderr                   ] [5c871be79cf3] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".

[2022-01-11T00:53:05,476][WARN ][stderr                   ] [5c871be79cf3] SLF4J: Defaulting to no-operation (NOP) logger implementation

[2022-01-11T00:53:05,477][WARN ][stderr                   ] [5c871be79cf3] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

[2022-01-11T00:53:06,516][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [5c871be79cf3] uncaught exception in thread [main]

org.opensearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to load plugin class [org.opensearch.security.OpenSearchSecurityPlugin]

at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:182) ~[opensearch-1.3.0.jar:1.3.0]

at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:169) ~[opensearch-1.3.0.jar:1.3.0]

at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100) ~[opensearch-1.3.0.jar:1.3.0]

at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) ~[opensearch-cli-1.3.0.jar:1.3.0]

at org.opensearch.cli.Command.main(Command.java:101) ~[opensearch-cli-1.3.0.jar:1.3.0]

at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:135) ~[opensearch-1.3.0.jar:1.3.0]

at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:101) ~[opensearch-1.3.0.jar:1.3.0]

Caused by: java.lang.IllegalStateException: failed to load plugin class [org.opensearch.security.OpenSearchSecurityPlugin]

at org.opensearch.plugins.PluginsService.loadPlugin(PluginsService.java:792) ~[opensearch-1.3.0.jar:1.3.0]

at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:728) ~[opensearch-1.3.0.jar:1.3.0]

at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:530) ~[opensearch-1.3.0.jar:1.3.0]

at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:193) ~[opensearch-1.3.0.jar:1.3.0]

at org.opensearch.node.Node.<init>(Node.java:396) ~[opensearch-1.3.0.jar:1.3.0]

at org.opensearch.node.Node.<init>(Node.java:319) ~[opensearch-1.3.0.jar:1.3.0]

at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-1.3.0.jar:1.3.0]

at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-1.3.0.jar:1.3.0]

at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:412) ~[opensearch-1.3.0.jar:1.3.0]

at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:178) ~[opensearch-1.3.0.jar:1.3.0]

... 6 more

Caused by: java.lang.reflect.InvocationTargetException

at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]

at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64) ~[?:?]

at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]

at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]

at java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[?:?]

at org.opensearch.plugins.PluginsService.loadPlugin(PluginsService.java:783) ~[opensearch-1.3.0.jar:1.3.0]

at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:728) ~[opensearch-1.3.0.jar:1.3.0]

at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:530) ~[opensearch-1.3.0.jar:1.3.0]

at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:193) ~[opensearch-1.3.0.jar:1.3.0]

at org.opensearch.node.Node.<init>(Node.java:396) ~[opensearch-1.3.0.jar:1.3.0]

at org.opensearch.node.Node.<init>(Node.java:319) ~[opensearch-1.3.0.jar:1.3.0]

at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-1.3.0.jar:1.3.0]

at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-1.3.0.jar:1.3.0]

at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:412) ~[opensearch-1.3.0.jar:1.3.0]

at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:178) ~[opensearch-1.3.0.jar:1.3.0]

... 6 more

Caused by: org.opensearch.OpenSearchException: plugins.security.ssl.transport.keystore_filepath or plugins.security.ssl.transport.server.pemcert_filepath and plugins.security.ssl.transport.client.pemcert_filepath must be set if transport ssl is requested.

at org.opensearch.security.ssl.DefaultSecurityKeyStore.initTransportSSLConfig(DefaultSecurityKeyStore.java:422) ~[?:?]

at org.opensearch.security.ssl.DefaultSecurityKeyStore.initSSLConfig(DefaultSecurityKeyStore.java:258) ~[?:?]

at org.opensearch.security.ssl.DefaultSecurityKeyStore.<init>(DefaultSecurityKeyStore.java:179) ~[?:?]

at org.opensearch.security.ssl.OpenSearchSecuritySSLPlugin.<init>(OpenSearchSecuritySSLPlugin.java:218) ~[?:?]

at org.opensearch.security.OpenSearchSecurityPlugin.<init>(OpenSearchSecurityPlugin.java:252) ~[?:?]

at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]

at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64) ~[?:?]

at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]

at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]

at java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[?:?]

at org.opensearch.plugins.PluginsService.loadPlugin(PluginsService.java:783) ~[opensearch-1.3.0.jar:1.3.0]

at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:728) ~[opensearch-1.3.0.jar:1.3.0]

at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:530) ~[opensearch-1.3.0.jar:1.3.0]

at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:193) ~[opensearch-1.3.0.jar:1.3.0]

at org.opensearch.node.Node.<init>(Node.java:396) ~[opensearch-1.3.0.jar:1.3.0]

at org.opensearch.node.Node.<init>(Node.java:319) ~[opensearch-1.3.0.jar:1.3.0]

at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-1.3.0.jar:1.3.0]

at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-1.3.0.jar:1.3.0]

at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:412) ~[opensearch-1.3.0.jar:1.3.0]

at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:178) ~[opensearch-1.3.0.jar:1.3.0]

... 6 more

Killing performance analyzer process 107

OpenSearch exited with code 1

Performance analyzer exited with code 143

uncaught exception in thread [main]

java.lang.IllegalStateException: failed to load plugin class [org.opensearch.security.OpenSearchSecurityPlugin]

Likely root cause: OpenSearchException[plugins.security.ssl.transport.keystore_filepath or plugins.security.ssl.transport.server.pemcert_filepath and plugins.security.ssl.transport.client.pemcert_filepath must be set if transport ssl is requested.]

at org.opensearch.security.ssl.DefaultSecurityKeyStore.initTransportSSLConfig(DefaultSecurityKeyStore.java:422)

at org.opensearch.security.ssl.DefaultSecurityKeyStore.initSSLConfig(DefaultSecurityKeyStore.java:258)

at org.opensearch.security.ssl.DefaultSecurityKeyStore.<init>(DefaultSecurityKeyStore.java:179)

at org.opensearch.security.ssl.OpenSearchSecuritySSLPlugin.<init>(OpenSearchSecuritySSLPlugin.java:218)

at org.opensearch.security.OpenSearchSecurityPlugin.<init>(OpenSearchSecurityPlugin.java:252)

at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)

at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)

at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)

at org.opensearch.plugins.PluginsService.loadPlugin(PluginsService.java:783)

at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:728)

at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:530)

at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:193)

at org.opensearch.node.Node.<init>(Node.java:396)

at org.opensearch.node.Node.<init>(Node.java:319)

at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242)

at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242)

at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:412)

at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:178)

at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:169)

at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100)

at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)

at org.opensearch.cli.Command.main(Command.java:101)

at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:135)

at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:101)
```

Previously the staging image was facing issues with the PA plugin not being present but now both the security plugin and PA are available so this should not be the case.

### To reproduce

1. Pull image: `docker pull opensearchstaging/opensearch:1.3.0`
2. Run: `docker run -p 9200:9200 -d -p 9600:9600 -e "discovery.type=single-node" opensearchstaging/opensearch:1.3.0`
3. Check logs once the container exits

### Expected behavior

Docker container comes up successfully for 1.3.0 staging tag

**Comment by gaiksaya** [comment]
Closing this issue since its a duplicate of https://github.com/opensearch-project/opensearch-build/issues/1185

**Comment by qreshi** [comment]
As mentioned in the description, both the security plugin and PA plugin are present in the Docker image so I don't think #1185 applies here

**Comment by gaiksaya** [comment]
Sorry my bad! Misread the description. Re-opening it. 
Need to debug if the issue is with security plugin or docker image itself.

**Comment by qreshi** [comment]
Just pulled the latest version of the OpenSearch 1.3.0 staging image and it looks like the error reported in this issue is not longer happening and OpenSearch is coming up successfully on it. I'm not sure if this was a change in the security plugin or something else but I'll close this issue in either case.

**Comment by kalpaitch** [comment]
I'm still getting it with:
```
opensearchproject/opensearch-dashboards   latest    a4962689e3f6   3 weeks ago     1.09GB
opensearchproject/opensearch              latest    feebbf30f81c   3 weeks ago     1.16GB
```
Error:
```
xxx     | [2023-04-11T09:36:19,045][WARN ][stderr                   ] [xxx] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
xxx     | [2023-04-11T09:36:19,046][WARN ][stderr                   ] [xxx] **SLF4J: Defaulting to no-operation (NOP) logger implementation**
xxx     | [2023-04-11T09:36:19,046][WARN ][stderr                   ] [xxx] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
xxx     | [2023-04-11T09:36:19,054][INFO ][o.o.s.s.t.SSLConfig      ] [xxx] SSL dual mode is disabled
xxx     | [2023-04-11T09:36:19,055][WARN ][o.o.s.OpenSearchSecurityPlugin] [xxx] OpenSearch Security plugin installed but disabled. This can expose your configuration (including passwords) to the public.
```
