### ISSUE TITLE
[BUG] TestAssembleUpload in Jenkins tests is throwing manifest not found error

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#1521]
```
jenkins.tests.TestBuildAssembleUpload > testJenkinsfile FAILED
    java.lang.reflect.UndeclaredThrowableException
        at com.sun.proxy.$Proxy23.accept(Unknown Source)
        at java.base/java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:671)
......
 at jenkins.tests.TestBuildAssembleUpload.testJenkinsfile(TestBuildAssembleUpload.groovy:52)

        Caused by:
        java.io.FileNotFoundException: builds/opensearch/manifest.yml (No such file or directory)
            at java.base/java.io.FileInputStream.open0(Native Method)
            at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
            at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
            at groovy.util.CharsetToolkit.<init>(CharsetToolkit.java:78)
```

Seems like it caused multiple PR from merging.
Thanks.

**Comment by peternied** [comment]
I'm looking into this issue

**Comment by peternied** [comment]
I cannot reproduce the failure locally

**Comment by peternied** [comment]
There have been no changes in the past 2 days, deleting the test to by time to resolve this issue correctly and unblock the build system

**Comment by dblock** [comment]
I bet you another test introduced recently that has an after block that deletes something it shouldn’t.
