### ISSUE TITLE
[Bug]: copyArtifactPermission path requires current job without path

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/opensearch-build#1566]
### Describe the bug

https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/opensearch-dashboards/distribution-build.jenkinsfile#L13

`copyArtifactPermission` currently takes the `JOB_NAME` provided. If you have a job called `jobA` and run the job from a nested location for example `Playground`, `JOB_NAME` will be `Playground\jobA`. So Jenkins will configure the run to allow permissions from `Playground\jobA` but Jenkins requires it to be `jobA`.

### To reproduce

Run an OpenSearch Dashboards job from a nested location. Notice the failure similar to this

```
hudson.AbortException: Unable to find project for artifact copy: Playground/avillk-distribution-build-opensearch-dashboards
This may be due to incorrect project name or permission settings; see help for project name in job configuration.
	at hudson.plugins.copyartifact.CopyArtifact.perform(CopyArtifact.java:452)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:99)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:69)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Expected behavior

Nested pipelines should be able to copy the artifact.

### Host / Environment

Jenkins

### Relevant log output

```shell
hudson.AbortException: Unable to find project for artifact copy: Playground/avillk-distribution-build-opensearch-dashboards
This may be due to incorrect project name or permission settings; see help for project name in job configuration.
	at hudson.plugins.copyartifact.CopyArtifact.perform(CopyArtifact.java:452)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:99)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:69)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by kavilla** [comment]
Use `JOB_BASE_NAME`
