### ISSUE TITLE
Migrate CfUrlRewriter Lambda from JavaScript to TypeScript

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-build#1654]
### Is your feature request related to a problem? Please describe

The current CfUrlRewriter is written as inline JavaScript code.

https://github.com/opensearch-project/opensearch-build/blob/main/deployment/lib/artifacts-public-access.ts#L23

Motivated by PR comment https://github.com/opensearch-project/opensearch-build/pull/1569#discussion_r795572203, we want to migrate 

1) the inline code to a separate file

2) JS to TS

### Describe the solution you'd like

Move logic to separate TS file

**Comment by tianleh** [comment]
Previous work https://github.com/tianleh/opensearch-build/pull/4

**Comment by tianleh** [comment]
Following this https://apoorv.blog/typescript-lambda-cdk/ to give a try. But failed due to 
<img width="1678" alt="Screen Shot 2022-02-18 at 12 30 26 AM" src="https://user-images.githubusercontent.com/60111637/154646483-817b0afc-88fa-4e23-a5ab-49c8a9a75ee4.png">

**Comment by tianleh** [comment]
Experimenting by following AWS doc https://docs.aws.amazon.com/cdk/v2/guide/serverless_example.html

**Comment by tianleh** [comment]
Create a test repo under my Github account to try out a TS Lambda function 

https://github.com/tianleh/cdk-examples/commits/main

**Comment by tianleh** [comment]
After adding the existing infra's Lambda logic https://github.com/tianleh/cdk-examples/commit/2bc242c6d2fe8f3462a7ec8e115be386141b3124, the cdk deployment is failing.

```
TsLambdaStack: creating CloudFormation changeset...
6:35:12 AM | UPDATE_FAILED        | AWS::Lambda::Function | helloWorldFn6540E6E1
Resource handler returned message: "Uploaded file must be a non-empty zip (Service: Lambda, Status Code: 400, Request ID: 6235940d-9ddf-48a8-8279-9c57f7c28ee5, Extended Request ID: null)" (RequestTok
en: fe974048-fbe2-6fc4-850e-d53b27f7e756, HandlerErrorCode: InvalidRequest)








 ❌  TsLambdaStack failed: Error: The stack named TsLambdaStack failed to deploy: UPDATE_ROLLBACK_COMPLETE
    at Object.waitForStackDeploy (/usr/share/opensearch/.nvm/versions/node/v16.14.0/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:309:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at prepareAndExecuteChangeSet (/usr/share/opensearch/.nvm/versions/node/v16.14.0/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:355:26)
    at CdkToolkit.deploy (/usr/share/opensearch/.nvm/versions/node/v16.14.0/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:201:24)
    at initCommandLine (/usr/share/opensearch/.nvm/versions/node/v16.14.0/lib/node_modules/aws-cdk/bin/cdk.ts:281:9)
The stack named TsLambdaStack failed to deploy: UPDATE_ROLLBACK_COMPLETE

```

**Comment by tianleh** [comment]
After removing unused imports https://github.com/tianleh/cdk-examples/commit/3ab3acf244caddcd35a6e2bc8e4773ea12a6e5a7 , cdk deployment is working again.

**Comment by tianleh** [comment]
Next try to make unit test work.

**Comment by tianleh** [comment]
```

npm run test

> ts-lambda@1.1.0 test
> jest

TypeError: Jest: a transform must export something.
    at /usr/share/opensearch/workspace/cdk-examples/ts-lambda/node_modules/@jest/transform/build/ScriptTransformer.js:386:19
    at async Promise.all (index 0)
    at async ScriptTransformer.loadTransformers (/usr/share/opensearch/workspace/cdk-examples/ts-lambda/node_modules/@jest/transform/build/ScriptTransformer.js:378:5)
    at async createScriptTransformer (/usr/share/opensearch/workspace/cdk-examples/ts-lambda/node_modules/@jest/transform/build/ScriptTransformer.js:1106:3)
    at async /usr/share/opensearch/workspace/cdk-examples/ts-lambda/node_modules/@jest/core/build/TestScheduler.js:269:31
    at async Promise.all (index 0)
    at async TestScheduler.scheduleTests (/usr/share/opensearch/workspace/cdk-examples/ts-lambda/node_modules/@jest/core/build/TestScheduler.js:262:5)
    at async runJest (/usr/share/opensearch/workspace/cdk-examples/ts-lambda/node_modules/@jest/core/build/runJest.js:387:19)
    at async _run10000 (/usr/share/opensearch/workspace/cdk-examples/ts-lambda/node_modules/@jest/core/build/cli/index.js:320:7)
    at async runCLI (/usr/share/opensearch/workspace/cdk-examples/ts-lambda/node_modules/@jest/core/build/cli/index.js:173:3)
```

**Comment by tianleh** [comment]
Fixed above with https://github.com/tianleh/cdk-examples/commit/c323e06d7cbaa63cbb2b9427b0872d24c9df9560

https://stackoverflow.com/questions/67691087/typeerror-jest-a-transform-must-export-something

**Comment by tianleh** [comment]
```
npm run test

> ts-lambda@1.1.0 test
> jest

 FAIL  test/ts-lambda.test.ts
  ● Test suite failed to run

    test/ts-lambda.test.ts:8:46 - error TS2345: Argument of type 'App' is not assignable to parameter of type 'Construct'.
      Types of property 'node' are incompatible.
        Type 'ConstructNode' is missing the following properties from type 'Node': _locked, _children, _context, _metadata, and 6 more.

    8     const stack = new TsLambda.TsLambdaStack(app, 'MyTestStack');
                                                   ~~~

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        5.126 s
Ran all test suites.
```

**Comment by tianleh** [comment]
This is the same error in my other experiment https://github.com/opensearch-project/opensearch-build/issues/1654#issuecomment-1044135834

**Comment by tianleh** [comment]
```
 npm run test

> ts-lambda@1.1.0 test
> jest

Bundling asset MyTestStack/helloWorldFn/Code/Stage...

 RUNS  test/ts-lambda.test.ts

  ..../tmp/cdk.outleOgjc/bundling-temp-3bd1d5a8ecd6b15e829fd7583897689b0a77892e2bd9241ed2691c76cd71597e/index.js  795b 
IAM Statement Changes
┌───┬────────────────────────────────────────┬────────┬────────────────┬──────────────────────────────┬───────────┐
│   │ Resource                               │ Effect │ Action         │ Principal                    │ Condition │
├───┼────────────────────────────────────────┼────────┼────────────────┼──────────────────────────────┼───────────┤
│ + │ ${helloWorldFnServiceRoleCB655CC3.Arn} │ Allow  │ sts:AssumeRole │ Service:lambda.amazonaws.com │           │
└───┴────────────────────────────────────────┴────────┴────────────────┴──────────────────────────────┴───────────┘
IAM Policy Changes
┌───┬────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────┐
│   │ Resource                           │ Managed Policy ARN                                                          │
├───┼────────────────────────────────────┼─────────────────────────────────────────────────────────────────────────────┤
│ + │ ${helloWorldFnServiceRoleCB655CC3} │ arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionR │
│   │                                    │ ole                                                                         │
└───┴────────────────────────────────────┴─────────────────────────────────────────────────────────────────────────────┘
(NOTE: There may be security-related changes not in this list. See https://github.com/aws/aws-cdk/issues/1299)

Resources
[+] AWS::IAM::Role helloWorldFnServiceRoleCB655CC3 
[+] AWS::Lambda::Function helloWorldFn6540E6E1 

--------------------------------------------------------------------------------------
{
  "Resources": {
    "helloWorldFnServiceRoleCB655CC3": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Statement": [
            {
              "Action": "sts:AssumeRole",
              "Effect": "Allow",
              "Principal": {
                "Service": "lambda.amazonaws.com"
              }
            }
          ],
          "Version": "2012-10-17"
        },
        "ManagedPolicyArns": [
          {
            "Fn::Join": [
              "",
              [
                "arn:",
                {
                  "Ref": "AWS::Partition"
                },
                ":iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
              ]
            ]
          }
        ]
      }
    },
    "helloWorldFn6540E6E1": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "Code": {
          "S3Bucket": {
            "Fn::Sub": "cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}"
          },
          "S3Key": "72de1bd093497c91abe6936fc1f1fe8aff244c34d606657a49f5f4ec3c57adcc.zip"
        },
        "Role": {
          "Fn::GetAtt": [
            "helloWorldFnServiceRoleCB655CC3",
            "Arn"
          ]
        },
        "Architectures": [
          "x86_64"
        ],
        "Environment": {
          "Variables": {
            "AWS_NODEJS_CONNECTION_REUSE_ENABLED": "1"
          }
        },
        "Handler": "index.myFunction",
        "MemorySize": 128,
        "Runtime": "nodejs14.x"
      },
      "DependsOn": [
        "helloWorldFnServiceRoleCB655CC3"
      ]
    }
  }
}
 FAIL  test/ts-lambda.test.ts (7.579 s)
  ✕ Empty Stack (640 ms)

  ● Empty Stack

    Template comparison produced unacceptable match

       9 |     const stack = new TsLambda.TsLambdaStack(app, 'MyTestStack');
      10 |     // THEN
    > 11 |     expectCDK(stack).to(matchTemplate({
         |                      ^
      12 |       "Resources": {}
      13 |     }, MatchStyle.EXACT))
      14 | });

      at StackMatchesTemplateAssertion.assertOrThrow (node_modules/@aws-cdk/assert/lib/assertions/match-template.ts:38:13)
      at StackInspector._to (node_modules/@aws-cdk/assert/lib/inspector.ts:25:15)
      at StackInspector.to (node_modules/@aws-cdk/assert/lib/inspector.ts:15:14)
      at Object.<anonymous> (test/ts-lambda.test.ts:11:22)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        7.65 s
```

**Comment by tianleh** [comment]
https://dashbird.io/blog/test-javascript-lambda-functions/

**Comment by tianleh** [comment]
Starting from scratch is easier and cleaner than migrating the existing code base. Still experimenting applying the TS knowledge from above to the infra's code base.

**Comment by tianleh** [comment]
See this error. Research a bit https://stackoverflow.com/a/59385041

<img width="1866" alt="Screen Shot 2022-02-20 at 2 01 29 PM" src="https://user-images.githubusercontent.com/60111637/154866224-d6572420-cb43-42e7-b0a8-891fb491fc6b.png">

**Comment by tianleh** [comment]
Fixed the error above by using the exact version package versions.

**Comment by tianleh** [comment]
```

The Lambda function associated with the CloudFront distribution is invalid or doesn't have the required permissions. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation. 
```
