### ISSUE TITLE
[Bug]: ci.sh fails for manifests/1.3.0/opensearch-1.3.0.yml

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-build#1661]
### Describe the bug

Run `./ci.sh manifests/1.3.0/opensearch-1.3.0.yml --snapshot`

Got this error which is failing the PR check.

```

BUILD FAILED in 1s
2022-02-21 20:14:28 ERROR    CI Manifest check failed
Traceback (most recent call last):
  File "./src/run_ci.py", line 25, in <module>
    sys.exit(main())
  File "./src/run_ci.py", line 21, in main
    CiManifests.from_file(args.manifest, args).check()
  File "/usr/share/opensearch/workspace/main-build/opensearch-build/src/ci_workflow/ci_manifest.py", line 21, in check
    self.__check__()
  File "/usr/share/opensearch/workspace/main-build/opensearch-build/src/ci_workflow/ci_input_manifest.py", line 36, in __check__
    ci_check_list.check()
  File "/usr/share/opensearch/workspace/main-build/opensearch-build/src/ci_workflow/ci_check_list_source.py", line 43, in check
    instance = klass(self.component, self.git_repo, self.target, check.args)
  File "/usr/share/opensearch/workspace/main-build/opensearch-build/src/ci_workflow/ci_check_gradle_properties.py", line 19, in __init__
    self.properties = self.__get_properties()
  File "/usr/share/opensearch/workspace/main-build/opensearch-build/src/ci_workflow/ci_check_gradle_properties.py", line 30, in __get_properties
    return PropertiesFile(self.git_repo.output(cmd))
  File "/usr/share/opensearch/workspace/main-build/opensearch-build/src/git/git_repository.py", line 78, in output
    return subprocess.check_output(command, cwd=cwd, shell=True).decode().strip()
  File "/usr/local/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command './gradlew properties -Dopensearch.version=1.3.0-SNAPSHOT -Dbuild.snapshot=true' returned non-zero exit status 1.
```

### To reproduce

Check the current main branch (e.g till https://github.com/opensearch-project/opensearch-build/commit/947bc5db651dd716a32dab953ebb85562f935bd7) and run `./ci.sh manifests/1.3.0/opensearch-1.3.0.yml --snapshot`

**Comment by gaiksaya** [comment]
Looks like issue with alerting plugin:
```
FAILURE: Build failed with an exception.

* Where:
Build file '/tmp/tmp1f3eej9k/alerting/build.gradle' line: 89

* What went wrong:
A problem occurred evaluating root project 'opensearch-alerting'.
> A problem occurred configuring project ':alerting'.
   > Cannot mutate content repository descriptor 'MavenLocal(file:/home/runner/.m2/repository/)' after repository has been used

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

**Comment by gaiksaya** [comment]
Can someone from @opensearch-project/alerting-plugin take a took?
Thanks!

**Comment by zelinh** [comment]
Issue with alerting is tracking here #1662

**Comment by peterzhuamazon** [comment]
[Triage] We have all the information about this issue, keep monitoring.

**Comment by peterzhuamazon** [comment]
This should be fixed for now, close issue.
Thanks,
