### ISSUE TITLE
[Bug]: Security plugin fails to complete build due to missing `plugin-descriptor.properties`

### ISSUE THREAD

**Issue by korpx-z** [opensearch-project/opensearch-build#1692]
### Describe the bug

When I try building the 1.3 stack, everything goes pretty well until security brings about this bug here:

```
2022-03-02 21:14:40 ERROR    Error building security, retry with: ./build.sh manifests/1.3.0/opensearch-1.3.0.yml --component security
Traceback (most recent call last):
  File "./src/run_build.py", line 79, in <module>
    sys.exit(main())
  File "./src/run_build.py", line 68, in main
    builder.export_artifacts(build_recorder)
  File "/opensearch-build/src/build_workflow/builder_from_source.py", line 64, in export_artifacts
    build_recorder.record_artifact(self.component.name, artifact_type, relative_path, absolute_path)
  File "/opensearch-build/src/build_workflow/build_recorder.py", line 40, in record_artifact
    BuildArtifactChecks.check(self.target, artifact_type, artifact_file)
  File "/opensearch-build/src/build_workflow/build_artifact_checks.py", line 42, in check
    instance.check(path)
  File "/opensearch-build/src/build_workflow/opensearch/build_artifact_check_plugin.py", line 22, in check
    data = zip.read("plugin-descriptor.properties").decode("UTF-8")
  File "/usr/lib/python3.7/zipfile.py", line 1464, in read
    with self.open(name, "r", pwd) as fp:
  File "/usr/lib/python3.7/zipfile.py", line 1503, in open
    zinfo = self.getinfo(name)
  File "/usr/lib/python3.7/zipfile.py", line 1431, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'plugin-descriptor.properties' in the archive"
```

### To reproduce

`./build.sh manifests/1.3.0/opensearch-1.3.0.yml`

### Expected behavior

A successful build! :D

### Host / Environment

x86
linux

**Comment by gaiksaya** [comment]
Hi @korpx-z ,

Can you try rebuilding again? There were few changes in last 2 hours to the security plugin branch in the manifest https://github.com/opensearch-project/opensearch-build/pull/1695
Thanks!

**Comment by abhinavGupta16** [comment]
[triage] @korpx-z - Do you have any updates on this issue? Thanks!

**Comment by korpx-z** [comment]
I was able to get around this issue by using tags/1.2.0.0 for the 1.2.0 stack. Now that I'm building 1.3, I am seeing this exact same error again, and I can't figure a way around it. There is no plugin-descriptor.properties file anywhere that I can copy, nor is there one generated if security is built separately. 

`2022-03-19 20:58:45 ERROR    Error building security, retry with: ./build.sh manifests/1.3.0/opensearch-1.3.0.yml --component security
Traceback (most recent call last):
  File "./src/run_build.py", line 80, in <module>
    sys.exit(main())
  File "./src/run_build.py", line 69, in main
    builder.export_artifacts(build_recorder)
  File "/opensearch-build/src/build_workflow/builder_from_source.py", line 65, in export_artifacts
    build_recorder.record_artifact(self.component.name, artifact_type, relative_path, absolute_path)
  File "/opensearch-build/src/build_workflow/build_recorder.py", line 40, in record_artifact
    BuildArtifactChecks.check(self.target, artifact_type, artifact_file)
  File "/opensearch-build/src/build_workflow/build_artifact_checks.py", line 42, in check
    instance.check(path)
  File "/opensearch-build/src/build_workflow/opensearch/build_artifact_check_plugin.py", line 22, in check
    data = zip.read("plugin-descriptor.properties").decode("UTF-8")
  File "/usr/lib/python3.7/zipfile.py", line 1464, in read
    with self.open(name, "r", pwd) as fp:
  File "/usr/lib/python3.7/zipfile.py", line 1503, in open
    zinfo = self.getinfo(name)
  File "/usr/lib/python3.7/zipfile.py", line 1431, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'plugin-descriptor.properties' in the archive"`

**Comment by dblock** [comment]
@korpx-z are you really on x86 (not x64)?

What happens when you do `./build.sh manifests/1.3.0/opensearch-1.3.0.yml --component security`?

Scroll through the output of that, are there any errors that aren't being noticed?

Can you check out https://github.com/opensearch-project/security, `git checkout 1.3` and `./gradlew assebmle`, what do you get?

**Comment by korpx-z** [comment]
Okay so it does look like this file is generated, but it ends up living in `/home/.gradle/daemon/<file-here>`
While opensearch-build seems to anticipate this file to be sitting in the packaged components root directory upon expansion. 

To resolve this error, I copied the properties file over to security's root directory, packaged it up, and placed it into the plugins/ dir. At this point, installing the plugin worked without any error.

**Comment by justinborromeo** [comment]
I'm still seeing this error when I run `./build.sh manifests/1.3.5/opensearch-1.3.5.yml --component security`.  

Also, `find . -name "*plugin-descriptor*"` doesn't return anything when run from `~/.gradle/daemon`.  Did the location of this file change?
