### ISSUE TITLE
[Bug]: job-scheduler failed to build for 1.3.0

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-build#1716]
### Describe the bug

Check this build errors
```

2022-03-08 01:40:13 ERROR    Error building job-scheduler, retry with: ./build.sh manifests/1.3.0/opensearch-1.3.0.yml --component job-scheduler
Traceback (most recent call last):
  File "./src/run_build.py", line 79, in <module>
    sys.exit(main())
  File "./src/run_build.py", line 67, in main
    builder.build(build_recorder)
  File "/var/jenkins/workspace/distribution-build-opensearch/src/build_workflow/builder_from_source.py", line 54, in build
    self.git_repo.execute(build_command)
  File "/var/jenkins/workspace/distribution-build-opensearch/src/git/git_repository.py", line 83, in execute
    subprocess.check_call(command, cwd=cwd, shell=True)
  File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'bash /tmp/tmpode0uf79/job-scheduler/scripts/build.sh -v 1.3.0 -p linux -a x64 -s false -o builds' returned non-zero exit status 1.
```

### To reproduce

Check out the repo locally and run build against job-scheduler

```

[opensearch@66605b868bfe opensearch-build]$ ./build.sh manifests/1.3.0/opensearch-1.3.0.yml --component job-scheduler
Installing dependencies in . ...
Installing dependencies from Pipfile.lock (16e10a)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Running ./src/run_build.py manifests/1.3.0/opensearch-1.3.0.yml --component job-scheduler ...
2022-03-08 01:50:35 INFO     Building in /tmp/tmpnv1sbnat
2022-03-08 01:50:35 INFO     Building OpenSearch (x64) into /usr/share/opensearch/projects/opensearch-build/builds/opensearch
2022-03-08 01:50:35 INFO     Skipping OpenSearch
2022-03-08 01:50:35 INFO     Skipping common-utils
2022-03-08 01:50:35 INFO     Building job-scheduler
2022-03-08 01:50:35 INFO     Executing "git init" in /tmp/tmpnv1sbnat/job-scheduler
2022-03-08 01:50:35 INFO     Executing "git remote add origin https://github.com/opensearch-project/job-scheduler.git" in /tmp/tmpnv1sbnat/job-scheduler
2022-03-08 01:50:35 INFO     Executing "git fetch --depth 1 origin main" in /tmp/tmpnv1sbnat/job-scheduler
2022-03-08 01:50:36 INFO     Executing "git checkout FETCH_HEAD" in /tmp/tmpnv1sbnat/job-scheduler
2022-03-08 01:50:36 INFO     Executing "git rev-parse HEAD" in /tmp/tmpnv1sbnat/job-scheduler
2022-03-08 01:50:36 INFO     Checked out https://github.com/opensearch-project/job-scheduler.git@main into /tmp/tmpnv1sbnat/job-scheduler at ec916373d2a20c268ff8e49a82bbadfbbbfb5c5b
2022-03-08 01:50:36 INFO     Executing "bash /tmp/tmpnv1sbnat/job-scheduler/scripts/build.sh -v 1.3.0 -p linux -a x64 -s false -o builds" in /tmp/tmpnv1sbnat/job-scheduler
+ getopts :h:v:s:o:p:a: arg
+ case $arg in
+ VERSION=1.3.0
+ getopts :h:v:s:o:p:a: arg
+ case $arg in
+ PLATFORM=linux
+ getopts :h:v:s:o:p:a: arg
+ case $arg in
+ ARCHITECTURE=x64
+ getopts :h:v:s:o:p:a: arg
+ case $arg in
+ SNAPSHOT=false
+ getopts :h:v:s:o:p:a: arg
+ case $arg in
+ OUTPUT=builds
+ getopts :h:v:s:o:p:a: arg
+ '[' -z 1.3.0 ']'
+ [[ false == \t\r\u\e ]]
+ '[' -z builds ']'
+ ./gradlew publishToMavenLocal -Dopensearch.version=1.3.0 -Dbuild.snapshot=false

FAILURE: Build failed with an exception.

* Where:
Build file '/tmp/tmpnv1sbnat/job-scheduler/build.gradle' line: 28

* What went wrong:
A problem occurred evaluating root project 'opensearch-job-scheduler'.
> Failed to apply plugin class 'org.opensearch.gradle.info.GlobalBuildInfoPlugin'.
   > Could not create plugin of type 'GlobalBuildInfoPlugin'.
      > Could not generate a decorated class for type GlobalBuildInfoPlugin.
         > org/gradle/jvm/toolchain/JavaInstallation

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 565ms
2022-03-08 01:50:37 ERROR    Error building job-scheduler, retry with: ./build.sh manifests/1.3.0/opensearch-1.3.0.yml --component job-scheduler
Traceback (most recent call last):
  File "./src/run_build.py", line 79, in <module>
    sys.exit(main())
  File "./src/run_build.py", line 67, in main
    builder.build(build_recorder)
  File "/usr/share/opensearch/projects/opensearch-build/src/build_workflow/builder_from_source.py", line 54, in build
    self.git_repo.execute(build_command)
  File "/usr/share/opensearch/projects/opensearch-build/src/git/git_repository.py", line 83, in execute
    subprocess.check_call(command, cwd=cwd, shell=True)
  File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'bash /tmp/tmpnv1sbnat/job-scheduler/scripts/build.sh -v 1.3.0 -p linux -a x64 -s false -o builds' returned non-zero exit status 1.
```

**Comment by dblock** [comment]
Closed via https://github.com/opensearch-project/opensearch-build/pull/1717

**Comment by tianleh** [comment]
@gaiksaya I just pulled in latest changes in the build repo to my local branch and can build 1.3.0 successfully

```

BUILD SUCCESSFUL in 27s
10 actionable tasks: 10 executed
++ find . -path '*build/distributions/*.zip'
+ zipPath=./build/distributions/opensearch-observability-1.3.0.0.zip
++ dirname ./build/distributions/opensearch-observability-1.3.0.0.zip
+ distributions=./build/distributions
+ echo 'COPY ./build/distributions/*.zip'
COPY ./build/distributions/*.zip
+ mkdir -p builds/plugins
+ cp ./build/distributions/opensearch-observability-1.3.0.0.zip ./builds/plugins
2022-03-08 18:36:12 INFO     Recording plugins artifact for opensearch-observability: plugins/opensearch-observability-1.3.0.0.zip (from /tmp/tmpka7tsntu/opensearch-observability/opensearch-observability/builds/plugins/opensearch-observability-1.3.0.0.zip)
2022-03-08 18:36:12 INFO     Checked /tmp/tmpka7tsntu/opensearch-observability/opensearch-observability/builds/plugins/opensearch-observability-1.3.0.0.zip (1.3.0.0)
2022-03-08 18:36:13 INFO     Created build manifest /usr/share/opensearch/workspace/opensearch-build/builds/opensearch/manifest.yml
2022-03-08 18:36:15 INFO     Done.
```

When you build, do you have the latest change from @dbbaughe https://github.com/opensearch-project/opensearch-build/pull/1717

**Comment by gaiksaya** [comment]
The most recent build at 8:43AM failed but recent one at 10:37AM passed. Looks good now.
Thanks @tianleh
