### ISSUE TITLE
[Bug]: Integration test for arm64 are failing in jenkins

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#1851]
### Describe the bug

The paths for opensearch in integration test workflow is being set to `https://ci.opensearch.org/ci/dbc/integ-test/1.3.1/1584/linux/arm64`

```
BUILD_ID: 1584
[Pipeline] library
Only using first definition of library jenkins
[Pipeline] readYaml
[Pipeline] echo
Artifact root URL: https://ci.opensearch.org/ci/dbc/integ-test/1.3.1/1584/linux/arm64
[Pipeline] echo
Paths: opensearch=https://ci.opensearch.org/ci/dbc/integ-test/1.3.1/1584/linux/arm64
[Pipeline] sh

+ ./test.sh integ-test manifests/1.3.1/opensearch-1.3.1-test.yml --paths opensearch=https://ci.opensearch.org/ci/dbc/integ-test/1.3.1/1584/linux/arm64
Installing dependencies in . ...

Warning: the environment variable LANG is not set!
We recommend setting this in ~/.profile (or equivalent) for proper expected behavior.
Creating a virtualenv for this project...
Pipfile: /var/jenkins/workspace/integ-test/Pipfile
Using /usr/local/bin/python3.7m (3.7.7) to create virtualenv...
created virtual environment CPython3.7.7.final.0-64 in 378ms
  creator CPython3Posix(dest=/usr/share/opensearch/.local/share/virtualenvs/integ-test-B5RGX0jA, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/usr/share/opensearch/.local/share/virtualenv)
    added seed packages: pip==21.3.1, setuptools==58.3.0, wheel==0.37.0
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator


Successfully created virtual environment!
Virtualenv location: /usr/share/opensearch/.local/share/virtualenvs/integ-test-B5RGX0jA
Installing dependencies from Pipfile.lock (16e10a)...

To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Running ./src/run_integ_test.py manifests/1.3.1/opensearch-1.3.1-test.yml --paths opensearch=https://ci.opensearch.org/ci/dbc/integ-test/1.3.1/1584/linux/arm64 ...
2022-03-30 00:49:45 INFO     Loading /var/jenkins/workspace/integ-test/manifests/1.3.1/opensearch-1.3.1-test.yml
2022-03-30 00:49:45 INFO     TestRecorder recording logs in /var/jenkins/workspace/integ-test/test-results/d9943ef65b1f4136becaa044bb19fa56/integ-test
2022-03-30 00:49:45 INFO     Loading https://ci.opensearch.org/ci/dbc/integ-test/1.3.1/1584/linux/arm64/dist/opensearch/manifest.yml
Traceback (most recent call last):
  File "./src/run_integ_test.py", line 33, in <module>
    sys.exit(main())
  File "./src/run_integ_test.py", line 24, in main
    all_results = IntegTestRunners.from_test_manifest(args, test_manifest).run()
  File "/var/jenkins/workspace/integ-test/src/test_workflow/integ_test/integ_test_runners.py", line 22, in from_test_manifest
    return cls.RUNNERS[test_manifest.name](args, test_manifest)
  File "/var/jenkins/workspace/integ-test/src/test_workflow/integ_test/integ_test_runner_opensearch.py", line 21, in __init__
    self.properties = IntegTestStartPropertiesOpenSearch(args.paths.get("opensearch", os.getcwd()))
  File "/var/jenkins/workspace/integ-test/src/test_workflow/integ_test/integ_test_start_properties_opensearch.py", line 13, in __init__
    super().__init__(path, "builds/opensearch/manifest.yml", "dist/opensearch/manifest.yml")
  File "/var/jenkins/workspace/integ-test/src/test_workflow/integ_test/integ_test_start_properties.py", line 20, in __init__
    self.bundle_manifest = BundleManifest.from_urlpath("/".join([self.path.rstrip("/"), self.bundle_dir]))
  File "/var/jenkins/workspace/integ-test/src/manifests/manifest.py", line 67, in from_urlpath
    return cls.from_url(file_or_url)
  File "/var/jenkins/workspace/integ-test/src/manifests/manifest.py", line 40, in from_url
    with urllib.request.urlopen(url) as f:
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

However for x64:
```
BUILD_ID: 1584
[Pipeline] library
Only using first definition of library jenkins
[Pipeline] readYaml
[Pipeline] echo
Artifact root URL: https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.1/1584/linux/x64
[Pipeline] echo
Paths: opensearch=https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.1/1584/linux/x64
```

### To reproduce

Try running `inetg-test` workflow for arm64

**Comment by kavilla** [comment]
`https://ci.opensearch.org/ci/dbc/integ-test/1.3.1/1584/linux/arm64` connected jobName should be the triggering job, we should convert this to an improvement task to allow for manual runs of the test job specifically because we didn't focus on the use case of running tests manually.

**Comment by gaiksaya** [comment]
The manual jobs are running well for x64. Not sure what is happening with arm64.

**Comment by ohltyler** [comment]
The root cause is likely related with [this line](https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/opensearch/integ-test.jenkinsfile#L49), which is reading an upstream build. Because the ARM test was a ‘rebuild’ of the x64 test, Jenkins might be reading the ‘integ-test’ job as the upstream build, and setting it as `integ-test` instead of the expected `distribution-build-opensearch`.

When I kicked off a clean integ-test build with the same ARM parameters (not as a rebuild), it looks to be running as expected.

**Comment by ohltyler** [comment]
Update: confirmed that Jenkins has an issue of reading rebuilt jobs as the upstream job: https://issues.jenkins.io/browse/JENKINS-61590

It may be worth adding a comment in the jenkinsfile to warn running as a rebuild may have issues, and to suggest to always kick off jobs as their own rather than rebuild.

**Comment by gaiksaya** [comment]
Created a PR to add this note. See linked PR.
