### ISSUE TITLE
[Bug]: tar package location of opensearch-performance-analyzer/opensearch_security.policy

### ISSUE THREAD

**Issue by tsgit** [opensearch-project/opensearch-build#2103]
### Describe the bug

unpacking the tar bundle for opensearch-1.3.2 places the pa security.policy in

./plugins/opensearch-performance-analyzer/pa_config/opensearch_security.policy

however the script opensearch-tar-install.sh adds 

-Djava.security.policy=....../config/opensearch-performance-analyzer/opensearch_security.policy

to config/jvm.options

see
https://github.com/opensearch-project/opensearch-build/blob/39e58d850ea3761a682400feba0d920562e19aeb/scripts/pkg/build_templates/opensearch/opensearch.rpm.spec#L100
https://github.com/opensearch-project/opensearch-build/blob/4597d77956a8d70905e03d135618de0ae912b316/scripts/legacy/tar/linux/opensearch-tar-install.sh#L29

thus on startup I see
```
[2022-05-06T13:56:24,437][WARN ][stderr                   ] [opensearch-log-test-node-1] java.util.ServiceConfigurationError: com.sun.tools.attach.spi.AttachProvider: Provider sun.tools.attach.AttachProviderImpl could not be instantiated
...
[2022-05-06T13:56:24,442][WARN ][stderr                   ] [opensearch-log-test-node-1] Caused by: java.security.AccessControlException: access denied ("com.sun.tools.attach.AttachPermission" "createAttachProvider")
```

### To reproduce

wget https://artifacts.opensearch.org/releases/bundle/opensearch/1.3.2/opensearch-1.3.2-linux-x64.tar.gz
tar xzf opensearch-1.3.2-linux-x64.tar.gz
cd opensearch-1.3.2
./opensearch-tar-install.sh

### Expected behavior

the security policy should be correctly loaded on startup

### Host / Environment

linux Fedora 35

### Relevant log output

```shell
[2022-05-06T13:56:24,437][WARN ][stderr                   ] [opensearch-log-test-node-1] java.util.ServiceConfigurationError: com.sun.tools.attach.spi.AttachProvider: Provider sun.tools.attach.AttachProviderImpl could not be instantiated
[2022-05-06T13:56:24,438][WARN ][stderr                   ] [opensearch-log-test-node-1]        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:582)
[2022-05-06T13:56:24,438][WARN ][stderr                   ] [opensearch-log-test-node-1]        at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:804)
[2022-05-06T13:56:24,438][WARN ][stderr                   ] [opensearch-log-test-node-1]        at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:722)
[2022-05-06T13:56:24,438][WARN ][stderr                   ] [opensearch-log-test-node-1]        at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1395)
[2022-05-06T13:56:24,438][WARN ][stderr                   ] [opensearch-log-test-node-1]        at jdk.attach/com.sun.tools.attach.spi.AttachProvider.providers(AttachProvider.java:260)
[2022-05-06T13:56:24,439][WARN ][stderr                   ] [opensearch-log-test-node-1]        at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:200)
[2022-05-06T13:56:24,439][WARN ][stderr                   ] [opensearch-log-test-node-1]        at org.opensearch.performanceanalyzer.jvm.ThreadList.runAttachDump(ThreadList.java:169)
[2022-05-06T13:56:24,439][WARN ][stderr                   ] [opensearch-log-test-node-1]        at org.opensearch.performanceanalyzer.jvm.ThreadList.lambda$runThreadDump$0(ThreadList.java:304)
[2022-05-06T13:56:24,439][WARN ][stderr                   ] [opensearch-log-test-node-1]        at org.opensearch.performanceanalyzer.core.Util.lambda$invokePrivileged$1(Util.java:57)
[2022-05-06T13:56:24,439][WARN ][stderr                   ] [opensearch-log-test-node-1]        at java.base/java.security.AccessController.doPrivileged(Native Method)
[2022-05-06T13:56:24,440][WARN ][stderr                   ] [opensearch-log-test-node-1]        at org.opensearch.performanceanalyzer.core.Util.invokePrivileged(Util.java:53)
[2022-05-06T13:56:24,440][WARN ][stderr                   ] [opensearch-log-test-node-1]        at org.opensearch.performanceanalyzer.jvm.ThreadList.runThreadDump(ThreadList.java:304)
[2022-05-06T13:56:24,440][WARN ][stderr                   ] [opensearch-log-test-node-1]        at org.opensearch.performanceanalyzer.jvm.ThreadList.getNativeTidMap(ThreadList.java:127)
[2022-05-06T13:56:24,440][WARN ][stderr                   ] [opensearch-log-test-node-1]        at org.opensearch.performanceanalyzer.collectors.OSMetricsCollector.collectMetrics(OSMetricsCollector.java:48)
[2022-05-06T13:56:24,440][WARN ][stderr                   ] [opensearch-log-test-node-1]        at org.opensearch.performanceanalyzer.collectors.PerformanceAnalyzerMetricsCollector.lambda$run$0(PerformanceAnalyzerMetricsCollector.java:67)
[2022-05-06T13:56:24,440][WARN ][stderr                   ] [opensearch-log-test-node-1]        at org.opensearch.performanceanalyzer.core.Util.lambda$invokePrivileged$1(Util.java:57)
[2022-05-06T13:56:24,441][WARN ][stderr                   ] [opensearch-log-test-node-1]        at java.base/java.security.AccessController.doPrivileged(Native Method)
[2022-05-06T13:56:24,441][WARN ][stderr                   ] [opensearch-log-test-node-1]        at org.opensearch.performanceanalyzer.core.Util.invokePrivileged(Util.java:53)
[2022-05-06T13:56:24,441][WARN ][stderr                   ] [opensearch-log-test-node-1]        at org.opensearch.performanceanalyzer.collectors.PerformanceAnalyzerMetricsCollector.run(PerformanceAnalyzerMetricsCollector.java:67)
[2022-05-06T13:56:24,441][WARN ][stderr                   ] [opensearch-log-test-node-1]        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2022-05-06T13:56:24,441][WARN ][stderr                   ] [opensearch-log-test-node-1]        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2022-05-06T13:56:24,442][WARN ][stderr                   ] [opensearch-log-test-node-1]        at java.base/java.lang.Thread.run(Thread.java:829)
[2022-05-06T13:56:24,442][WARN ][stderr                   ] [opensearch-log-test-node-1] Caused by: java.security.AccessControlException: access denied ("com.sun.tools.attach.AttachPermission" "createAttachProvider")
[2022-05-06T13:56:24,442][WARN ][stderr                   ] [opensearch-log-test-node-1]        at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
[2022-05-06T13:56:24,442][WARN ][stderr                   ] [opensearch-log-test-node-1]        at java.base/java.security.AccessController.checkPermission(AccessController.java:897)
[2022-05-06T13:56:24,443][WARN ][stderr                   ] [opensearch-log-test-node-1]        at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
[2022-05-06T13:56:24,443][WARN ][stderr                   ] [opensearch-log-test-node-1]        at jdk.attach/com.sun.tools.attach.spi.AttachProvider.<init>(AttachProvider.java:93)
[2022-05-06T13:56:24,443][WARN ][stderr                   ] [opensearch-log-test-node-1]        at jdk.attach/sun.tools.attach.HotSpotAttachProvider.<init>(HotSpotAttachProvider.java:47)
[2022-05-06T13:56:24,443][WARN ][stderr                   ] [opensearch-log-test-node-1]        at jdk.attach/sun.tools.attach.AttachProviderImpl.<init>(AttachProviderImpl.java:38)
[2022-05-06T13:56:24,443][WARN ][stderr                   ] [opensearch-log-test-node-1]        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2022-05-06T13:56:24,443][WARN ][stderr                   ] [opensearch-log-test-node-1]        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2022-05-06T13:56:24,444][WARN ][stderr                   ] [opensearch-log-test-node-1]        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2022-05-06T13:56:24,444][WARN ][stderr                   ] [opensearch-log-test-node-1]        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2022-05-06T13:56:24,444][WARN ][stderr                   ] [opensearch-log-test-node-1]        at java.base/java.util.ServiceLoader$ProviderImpl$2.run(ServiceLoader.java:788)
[2022-05-06T13:56:24,444][WARN ][stderr                   ] [opensearch-log-test-node-1]        at java.base/java.security.AccessController.doPrivileged(Native Method)
[2022-05-06T13:56:24,444][WARN ][stderr                   ] [opensearch-log-test-node-1]        at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:793)
[2022-05-06T13:56:24,444][WARN ][stderr                   ] [opensearch-log-test-node-1]        ... 20 more
```

**Comment by tsgit** [comment]
apparently the missing step is to copy 
./plugins/opensearch-performance-analyzer/pa_config/opensearch_security.policy
into
./config/opensearch-performance-analyzer/

**Comment by peterzhuamazon** [comment]
@sruti1312 @sgup432 please take a look at this.
Thanks.
