### ISSUE TITLE
[Distribution] Broken build `could not find java in JAVA_HOME at /opt/java/openjdk-17/bin/java`

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#2120]
Looks like the 2.0.0 build is broken, could be a job scheduler or OpenSearch core issue.

```
2022-05-13 16:11:22 INFO     Executing "/tmp/tmpnfqjtty1/opensearch-2.0.0/bin/opensearch-plugin install --batch file:/tmp/tmpnfqjtty1/opensearch-job-scheduler-2.0.0.0.zip" in /tmp/tmpnfqjtty1/opensearch-2.0.0
could not find java in JAVA_HOME at /opt/java/openjdk-17/bin/java
Traceback (most recent call last):
  File "./src/run_assemble.py", line 58, in <module>
    sys.exit(main())
  File "./src/run_assemble.py", line 44, in main
    bundle.install_components()
  File "/var/jenkins/workspace/distribution-build-opensearch/src/assemble_workflow/bundle.py", line 77, in install_components
    self.install_plugin(c)
  File "/var/jenkins/workspace/distribution-build-opensearch/src/assemble_workflow/bundle_opensearch.py", line 22, in install_plugin
    self._execute(f"{cli_path} install --batch file:{tmp_path}")
  File "/var/jenkins/workspace/distribution-build-opensearch/src/assemble_workflow/bundle.py", line 106, in _execute
    subprocess.check_call(command, cwd=self.min_dist.archive_path, shell=True)
  File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/tmp/tmpnfqjtty1/opensearch-2.0.0/bin/opensearch-plugin install --batch file:/tmp/tmpnfqjtty1/opensearch-job-scheduler-2.0.0.0.zip' returned non-zero exit status 1.
```

**Comment by peterzhuamazon** [comment]
Will issue a fix very soon.

**Comment by peternied** [comment]
@peterzhuamazon could you close after we have a successful build or a new build issue that is being worked on?

**Comment by peterzhuamazon** [comment]
We should close it when the related issue is resolved, not build.
