### ISSUE TITLE
[Bug]: Not possible to configure Opensearch docker container as coordinating node

### ISSUE THREAD

**Issue by smlx** [opensearch-project/opensearch-build#2129]
### Describe the bug

It doesn't seem possible to configure the opensearch docker container to run as a coordinating node.

The documented way to configure node roles is to set the `node.roles` environment variable to a list e.g. `node.roles=master,data`. However coordinating nodes have an empty `node.roles`. Setting the `node.roles` to an empty string fails due to [this code](https://github.com/opensearch-project/opensearch-build/blob/aa2f3d401527f86eb99410c1e697a9e032013b3a/docker/release/config/opensearch/opensearch-docker-entrypoint.sh#L92) in the docker entrypoint which ignores empty environment variables. However even if you set `node.roles=" "` to get past that check in the entrypoint, it seems that opensearch will ignore the empty variable and revert to the default set of roles.

It may still be possible to configure a coordinating node using the legacy role configuration method. See [this discussion](https://forum.opensearch.org/t/problem-with-coordinating-node-role/8794/3) for an example. However that configuration method is now deprecated.

### To reproduce

Run the opensearch docker container in a cluster with an empty list of `node.roles`. You can do this easily via the helm chart.

### Expected behavior

There should be a documented method to configure a coordinating node using the new `node.roles` configuration API.

### Screenshots

n/a

### Host / Environment

Opensearch helm chart v1.11 running on kubernetes.

### Additional context

I tried the following values for the `node.roles` environment variable. None of them worked to configure a coordinating node. They all either threw an unknown role error or fell back to the default roles.

* `[]`
* `,`
* ` ` (a space)

### Relevant log output

For `node.roles="[]"`:
```
java.lang.IllegalArgumentException: unknown role []
	at org.opensearch.cluster.node.DiscoveryNode.getRoleFromRoleName(DiscoveryNode.java:569)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.opensearch.common.settings.Setting.lambda$listSetting$47(Setting.java:1865)
	at org.opensearch.common.settings.Setting.get(Setting.java:464)
	at org.opensearch.common.settings.Setting.get(Setting.java:458)
	at org.opensearch.cluster.node.DiscoveryNode.getRolesFromSettings(DiscoveryNode.java:275)
	at org.opensearch.cluster.node.DiscoveryNode.isDataNode(DiscoveryNode.java:106)
	at org.opensearch.env.NodeEnvironment.<init>(NodeEnvironment.java:345)
	at org.opensearch.node.Node.<init>(Node.java:414)
	at org.opensearch.node.Node.<init>(Node.java:319)
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242)
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242)
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:412)
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:178)
	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:169)
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
	at org.opensearch.cli.Command.main(Command.java:101)
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:135)
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:101)
```

For `node.roles=" "`:

```
[2022-05-17T08:19:48,184][INFO ][o.o.n.Node               ] [opensearch-cluster-coordinating-2] node name [opensearch-cluster-coordinating-2], node ID [rKGOZJhlSemjuOm900sQvw], cluster name [opensearch-cluster], roles [master, remote_cluster_client, data, ingest]
```

**Comment by smlx** [comment]
I just wanted to note that this bug is cluster-destroying if you have coordinating nodes configured without persistence, and then upgrade to the newer role configuration method. Suddenly you have a bunch of master nodes without persistent storage which will cause the cluster to permanently lose quorum once they restart and change IDs.

**Comment by dblock** [comment]
Looks like a real bug, thanks for reporting. Would definitely appreciate a fix!

**Comment by zelinh** [comment]
[Triage] Thanks for letting us know this. We will look into this.

**Comment by prudhvigodithi** [comment]
Hey @smlx, thanks for reporting, but I assume that is the behavior. Every node is implicitly a coordinating node (Ref: https://opensearch.org/docs/latest/opensearch/cluster/) which means node that has an explicit empty list of roles will act as a coordinating node. I was able to reproduce your issue 
## Error Reproduced
```
pgodithi$ k logs opensearch-cluster-master-0  -f -n os | grep roles
[2022-05-17T21:22:24,763][INFO ][o.o.n.Node               ] [opensearch-cluster-master-0] node name [opensearch-cluster-master-0], node ID [1JMyqkefRDe2OBwfj14unQ], cluster name [opensearch-cluster], roles [master, remote_cluster_client, data, ingest]
```
I was able to fix it with helm by adding: 
https://github.com/prudhvigodithi/helm-charts/blob/coordinating-role/charts/opensearch/values.yaml#L11
https://github.com/prudhvigodithi/helm-charts/blob/coordinating-role/charts/opensearch/values.yaml#L45

```
pgodithi$ k logs opensearch-cluster-master-0  -f -n os  | grep -i roles
[2022-05-18T00:26:28,940][INFO ][o.o.n.Node               ] [opensearch-cluster-master-0] node name [opensearch-cluster-master-0], node ID [exmGbGCTR3OuGkeobbDZ2Q], cluster name [opensearch-cluster], roles []
```

Once you have added this try to run this curl command to get the node role 
`curl -XGET https://localhost:9200/_cat/nodes?h=nodeRole  -u 'admin:admin' --insecure`
The above should output the role in short-form

Please test and let us know @smlx.
@bbarani @dblock

**Comment by smlx** [comment]
Yes, I'm aware you can configure an empty `node.roles` list by setting it directly in the configuration file as you did in https://github.com/prudhvigodithi/helm-charts/blob/coordinating-role/charts/opensearch/values.yaml#L45.

The bug is that https://github.com/prudhvigodithi/helm-charts/blob/coordinating-role/charts/opensearch/values.yaml#L11 by itself should work to configure a coordinating node, and it does not.

**Comment by prudhvigodithi** [comment]
Hey @smlx this seems to be like a behavior from app side, for coordinating node passing `node.roles: []` opensearch yaml file is allowed, but its not picked up from empty env value. However if I disable the if condition from the entrypoint code I get the following error `ERROR: setting [node.roles] must not be empty`. 
@saratvemulapalli any thoughts please?

**Comment by saratvemulapalli** [comment]
Took a look at this. Thanks @prudhvigodithi for the context. 
I didnt know OpenSearch supports loading configuration via ENV variables. 

This seems like a bug to me that, `opensearch.yml` does support `node.roles=[]` which defaults to coordinating node only but it doesnt support when passed via ENV/OPTS variables. 

Thanks for reporting this @smlx. Are you open to contributing a fix to OpenSearch?
Short term, you should be able to work with the suggestion from @prudhvigodithi. Longer term we should fix it in OpenSearch.

**Comment by smlx** [comment]
> Thanks for reporting this @smlx. Are you open to contributing a fix to OpenSearch?

Sorry I don't really have time for this. It looks like the fix will require changes to the Opensearch environment variable configuration parsing, associated regression testing etc.

> Short term, you should be able to work with the suggestion from @prudhvigodithi. Longer term we should fix it in OpenSearch.

That workaround isn't really viable since it requires replacing the entire upstream helm chart configuration. I found another workaround which is to give the coordinating node the `ingest` role since a) it doesn't require persistent storage, and b) I don't use ingest pipelines. So it effectively becomes a coordinating node anyway.

**Comment by prudhvigodithi** [comment]
I have raised as a bug in OpenSearch repo: https://github.com/opensearch-project/OpenSearch/issues/3412
