### ISSUE TITLE
JS Tests in build repo is omitting warnings and possible errors

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#2134]
https://github.com/opensearch-project/opensearch-build/blob/main/.github/workflows/js-tests.yml
https://github.com/opensearch-project/opensearch-build/runs/6480088304?check_suite_focus=true#step:3:1

This seems like github actions issues not related to our code.
```
Warning: Unexpected input(s) 'cache', valid inputs are ['always-auth', 'node-version', 'registry-url', 'scope', 'version']
Run actions/setup-node@v1
  with:
    node-version: 12.x
    cache: npm
    always-auth: false
/opt/hostedtoolcache/node/12.22.12/x64/bin/node --version
v12.22.12
/opt/hostedtoolcache/node/12.22.12/x64/bin/npm --version
6.14.16
```

------

This seems like some errors get omitted and skipped.

```
Run yarn test -- --coverage
  yarn test -- --coverage
  shell: /usr/bin/bash -e {0}
yarn run v1.22.18
warning package.json: No license field
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
$ jest --coverage
PASS test/lambdas/cf-url-rewriter/cf-url-rewriter.test.ts
  ● Console

    console.log
      Error: Error getting!
          at Object.<anonymous> (/home/runner/work/opensearch-build/opensearch-build/deployment/test/lambdas/cf-url-rewriter/cf-url-rewriter.test.ts:108:15)
          at /home/runner/work/opensearch-build/opensearch-build/deployment/node_modules/jest-mock/build/index.js:444:39
          at Object.<anonymous> (/home/runner/work/opensearch-build/opensearch-build/deployment/node_modules/jest-mock/build/index.js:452:13)
          at Object.https_get_1 (/home/runner/work/opensearch-build/opensearch-build/deployment/node_modules/jest-mock/build/index.js:166:19)
          at Object.httpsGet (eval at _createMockFunction (/home/runner/work/opensearch-build/opensearch-build/deployment/node_modules/jest-mock/build/index.js:625:31), <anonymous>:1:52)
          at Object.handler (/home/runner/work/opensearch-build/opensearch-build/deployment/lambdas/cf-url-rewriter/cf-url-rewriter.ts:17:37)
          at Object.<anonymous> (/home/runner/work/opensearch-build/opensearch-build/deployment/test/lambdas/cf-url-rewriter/cf-url-rewriter.test.ts:111:11)
          at Object.asyncJestTest (/home/runner/work/opensearch-build/opensearch-build/deployment/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:106:37)
          at /home/runner/work/opensearch-build/opensearch-build/deployment/node_modules/jest-jasmine2/build/queueRunner.js:45:12
          at new Promise (<anonymous>)

      at Object.handler (lambdas/cf-url-rewriter/cf-url-rewriter.ts:25:21)

Bundling asset MyTestStack/CfUrlRewriter/Code/Stage...
warning package.json: No license field
$ /home/runner/work/opensearch-build/opensearch-build/deployment/node_modules/.bin/esbuild --bundle /home/runner/work/opensearch-build/opensearch-build/deployment/lambdas/cf-url-rewriter/cf-url-rewriter.ts --target=node14 --platform=node --outfile=/tmp/cdk.outDQn4ls/bundling-temp-37e896dc19f7b2ae3bea0f30f2b48488d7bab12bf2830d59920c7dba378d6452/index.js --minify --external:aws-sdk

  ...c19f7b2ae3bea0f30f2b48488d7bab12bf2830d59920c7dba378d6452/index.js  1.7kb

Bundling asset MyTestStack/CfUrlRewriter/Code/Stage...
warning package.json: No license field
$ /home/runner/work/opensearch-build/opensearch-build/deployment/node_modules/.bin/esbuild --bundle /home/runner/work/opensearch-build/opensearch-build/deployment/lambdas/cf-url-rewriter/cf-url-rewriter.ts --target=node14 --platform=node --outfile=/tmp/cdk.outMHTwws/bundling-temp-88aa51e1fb1bcd8a81ce9656dd91f8550e79e57bd4d37b85168ca8fb4f7f25bc/index.js --minify --external:aws-sdk

  ...1fb1bcd8a81ce9656dd91f8550e79e57bd4d37b85168ca8fb4f7f25bc/index.js  1.7kb

PASS test/build-artifact-stack.test.ts
PASS test/lambdas/cf-url-rewriter/https-get.test.ts
  ● Console

    console.log
      SyntaxError: Unexpected token r in JSON at position 0
          at JSON.parse (<anonymous>)
          at Stream.<anonymous> (/home/runner/work/opensearch-build/opensearch-build/deployment/lambdas/cf-url-rewriter/https-get.ts:17:37)
          at Stream.emit (events.js:314:20)
          at Object.<anonymous> (/home/runner/work/opensearch-build/opensearch-build/deployment/test/lambdas/cf-url-rewriter/https-get.test.ts:34:16)
          at /home/runner/work/opensearch-build/opensearch-build/deployment/node_modules/jest-mock/build/index.js:444:39
          at Object.<anonymous> (/home/runner/work/opensearch-build/opensearch-build/deployment/node_modules/jest-mock/build/index.js:452:13)
          at Object.get (/home/runner/work/opensearch-build/opensearch-build/deployment/node_modules/jest-mock/build/index.js:166:19)
          at /home/runner/work/opensearch-build/opensearch-build/deployment/lambdas/cf-url-rewriter/https-get.ts:7:31
          at new Promise (<anonymous>)
          at Object.httpsGet (/home/runner/work/opensearch-build/opensearch-build/deployment/lambdas/cf-url-rewriter/https-get.ts:5:12)

      at Stream.<anonymous> (lambdas/cf-url-rewriter/https-get.ts:20:29)

    console.log
      Stream {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: undefined,
        [Symbol(kCapture)]: false
      }

      at lambdas/cf-url-rewriter/https-get.ts:29:21

-----------------------------|---------|----------|---------|---------|-------------------
File                         | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
-----------------------------|---------|----------|---------|---------|-------------------
All files                    |     100 |      100 |     100 |     100 |                   
 lambdas/cf-url-rewriter     |     100 |      100 |     100 |     100 |                   
  cf-url-rewriter.ts         |     100 |      100 |     100 |     100 |                   
  https-get.ts               |     100 |      100 |     100 |     100 |                   
 lib                         |     100 |      100 |     100 |     100 |                   
  artifacts-public-access.ts |     100 |      100 |     100 |     100 |                   
  buckets.ts                 |     100 |      100 |     100 |     100 |                   
  build-artifact-stack.ts    |     100 |      100 |     100 |     100 |                   
  identities.ts              |     100 |      100 |     100 |     100 |                   
-----------------------------|---------|----------|---------|---------|-------------------

Test Suites: 3 passed, 3 total
Tests:       13 passed, 13 total
Snapshots:   0 total
Time:        7.414 s
Ran all test suites.
Done in 8.05s.
```

**Comment by peterzhuamazon** [comment]
We will close this for now as the code is moved to opensearch-ci.

**Comment by peterzhuamazon** [comment]
This is fixed now after the migration.
