### ISSUE TITLE
[BUG] Bundle manifest not defined correctly 

### ISSUE THREAD

**Issue by setiah** [opensearch-project/opensearch-build#252]
**Describe the bug**
The expected syntax for bundle manifest file is #111 . The [test infra expects a bunch of parameters](https://github.com/opensearch-project/opensearch-build/blob/main/bundle-workflow/python/manifests/bundle_manifest.py#L12) which are missing in the manifest file and because of that it breaks. 

```
Traceback (most recent call last):
  File "python/test.py", line 17, in <module>
    manifest = BundleManifest.from_file(args.manifest)
  File "/home/ubuntu/cicd/opensearch-build/bundle-workflow/python/manifests/bundle_manifest.py", line 29, in from_file
    return BundleManifest(yaml.safe_load(file))
  File "/home/ubuntu/cicd/opensearch-build/bundle-workflow/python/manifests/bundle_manifest.py", line 35, in __init__
    self.build = self.Build(data['build'])
  File "/home/ubuntu/cicd/opensearch-build/bundle-workflow/python/manifests/bundle_manifest.py", line 51, in __init__
    self.architecture = data['architecture']
KeyError: 'architecture'
```

**Reproduce**
Run the test.py from `main` branch of opensearch-build repo

`~/opensearch-build/bundle-workflow$ python python/test.py --manifest /home/ubuntu/cicd/opensearch-build/manifests/opensearch-1.0.0.yml`

**Comment by camerski** [comment]
@setiah You have confused bundle and input manifests.
