### ISSUE TITLE
Add support s390x

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#2836]
### Is your feature request related to a problem? Please describe

Add support for IBM s390x platform.

### Describe the solution you'd like

- [ ] Docker release

### Additional context

Coming from https://github.com/opensearch-project/OpenSearch/issues/4000

**Comment by dblock** [comment]
@bbarani What are all the things one would need to do to truly support s390x?

**Comment by prudhvigodithi** [comment]
[Triaged] Adding @elfisher @setiah @bbarani to add more insights.

**Comment by francesco-defalco** [comment]
Thank you for your support, in general with an Ubuntu 18.04 and docker engine 20.10.21 I finally was able to run a single node with a basic configuration "docker run -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" phoenixsystemsag/opensearch:2.3.0"

Now I am focusing to run this image with custom configuration (jvm.options and opensearch.yml) files.

Best regards

**Comment by prudhvigodithi** [comment]
Cool, thanks for the update @francesco-defalco.

**Comment by francesco-defalco** [comment]
Hi @dblock, @prudhvigodithi 

I would like update about my tests about s390x platform, it seems that the security manager in Opensearch has some compatibility problems with s390x platform:

```
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap.OpenSearch (file:/usr/share/opensearch/lib/opensearch-2.3.0.jar)
WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.OpenSearch
WARNING: System::setSecurityManager will be removed in a future release
[2022-11-10T12:43:24,231][WARN ][o.o.b.JNANatives         ] [node-1] unable to install syscall filter:
java.lang.UnsupportedOperationException: seccomp unavailable: 's390x' architecture unsupported
        at org.opensearch.bootstrap.SystemCallFilter.linuxImpl(SystemCallFilter.java:282) ~[opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.bootstrap.SystemCallFilter.init(SystemCallFilter.java:664) ~[opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.bootstrap.JNANatives.tryInstallSystemCallFilter(JNANatives.java:281) [opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.bootstrap.Natives.tryInstallSystemCallFilter(Natives.java:128) [opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:129) [opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:191) [opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404) [opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180) [opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:171) [opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104) [opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) [opensearch-cli-2.3.0.jar:2.3.0]
        at org.opensearch.cli.Command.main(Command.java:101) [opensearch-cli-2.3.0.jar:2.3.0]
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:137) [opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:103) [opensearch-2.3.0.jar:2.3.0]
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap.Security (file:/usr/share/opensearch/lib/opensearch-2.3.0.jar)
WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.Security
WARNING: System::setSecurityManager will be removed in a future release

```

I leave here some piece of my opensearch.yml
`# ---------------------------------- Various -----------------------------------
#
# Require explicit names when deleting indices:
#
#action.destructive_requires_name: true
#---------CONFIG--------#
plugins.security.ssl.transport.pemcert_filepath: node.pem
plugins.security.ssl.transport.pemkey_filepath: node-key.pem
plugins.security.ssl.transport.pemtrustedcas_filepath: root-ca.pem
plugins.security.ssl.transport.enforce_hostname_verification: false
plugins.security.ssl.http.enabled: true
plugins.security.ssl.http.pemcert_filepath: node.pem
plugins.security.ssl.http.pemkey_filepath: node-key.pem
plugins.security.ssl.http.pemtrustedcas_filepath: root-ca.pem
plugins.security.allow_unsafe_democertificates: true
plugins.security.allow_default_init_securityindex: true
plugins.security.authcz.admin_dn:
    - CN=kirk,OU=client,O=client,L=test, C=de
plugins.security.audit.type: internal_opensearch
plugins.security.enable_snapshot_restore_privilege: false
plugins.security.check_snapshot_restore_write_privileges: false
plugins.security.restapi.roles_enabled:
    ["all_access", "security_rest_api_access"]
plugins.security.system_indices.enabled: true
plugins.security.system_indices.indices:
    [
        ".opendistro-alerting-config",
        ".opendistro-alerting-alert*",
        ".opendistro-anomaly-results*",
        ".opendistro-anomaly-detector*",
        ".opendistro-anomaly-checkpoints",
        ".opendistro-anomaly-detection-state",
        ".opendistro-reports-",
        ".opendistro-notifications-",
        ".opendistro-notebooks",
        ".opendistro-asynchronous-search-response*",
        ".replication-metadata-store",
    ]
node.max_local_storage_nodes: 1
plugins.security.disabled: false
path.data: /usr/share/opensearch/data/`


Thank you

**Comment by dblock** [comment]
@francesco-defalco That code is in OpenSearch? Open separate issues and leave this one as the umbrella for s390x release.
