### ISSUE TITLE
[BUG] Missing performance analyzer configuration files

### ISSUE THREAD

**Issue by guillaume-alvarez** [opensearch-project/opensearch-build#3042]
**Describe the bug**
When using opensearch 2.3.0 or 2.4.1 docker the content of /usr/share/opensearch/logs/performance-analyzer.log contains errors about configuration files:
```
11:18:56.798 [rca-controller] ERROR org.opensearch.performanceanalyzer.rca.RcaController - Error reading file /usr/share/opensearch/data/rca_enabled.conf
java.nio.file.NoSuchFileException: /usr/share/opensearch/data/rca_enabled.conf
....
11:18:57.402 [pa-reader] ERROR org.opensearch.performanceanalyzer.reader.ReaderMetricsProcessor - Error reading file '/usr/share/opensearch/data/batch_metrics_enabled.conf': java.nio.file.NoSuchFileException: /usr/share/opensearch/data/batch_metrics_enabled.conf
```

**To Reproduce**
1. start opensearch 2.4.1 with `docker run -d -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" opensearchproject/opensearch:latest`
2. Open a shell inside the docker.
3. `head -n 50 execute tail -f  /usr/share/opensearch/logs/performance-analyzer.log`

**Expected behavior**
No error with default conf.

**Plugins**
No specific configuration.
Performance-analyzer is enabled by default.

**Screenshots**
logs:
```
11:18:56.798 [rca-controller] ERROR org.opensearch.performanceanalyzer.rca.RcaController - Error reading file /usr/share/opensearch/data/rca_enabled.conf
java.nio.file.NoSuchFileException: /usr/share/opensearch/data/rca_enabled.conf
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:380) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:432) ~[?:?]
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422) ~[?:?]
	at java.nio.file.Files.newInputStream(Files.java:160) ~[?:?]
	at java.util.Scanner.<init>(Scanner.java:718) ~[?:?]
	at org.opensearch.performanceanalyzer.rca.RcaController.lambda$readRcaEnabledFromConf$1(RcaController.java:344) ~[performance-analyzer-rca-2.3.0.0.jar:?]
	at org.opensearch.performanceanalyzer.core.Util.lambda$invokePrivileged$1(Util.java:57) ~[performance-analyzer-rca-2.3.0.0.jar:?]
	at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]
	at org.opensearch.performanceanalyzer.core.Util.invokePrivileged(Util.java:53) ~[performance-analyzer-rca-2.3.0.0.jar:?]
	at org.opensearch.performanceanalyzer.rca.RcaController.readRcaEnabledFromConf(RcaController.java:342) ~[performance-analyzer-rca-2.3.0.0.jar:?]
	at org.opensearch.performanceanalyzer.rca.RcaController.run(RcaController.java:300) ~[performance-analyzer-rca-2.3.0.0.jar:?]
	at org.opensearch.performanceanalyzer.PerformanceAnalyzerApp.lambda$startRcaTopLevelThread$0(PerformanceAnalyzerApp.java:173) ~[performance-analyzer-rca-2.3.0.0.jar:?]
	at org.opensearch.performanceanalyzer.threads.ThreadProvider.lambda$createThreadForRunnable$0(ThreadProvider.java:45) ~[performance-analyzer-rca-2.3.0.0.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
11:18:57.042 [pa-reader] ERROR org.opensearch.performanceanalyzer.reader.ReaderMetricsProcessor - Error reading file '/usr/share/opensearch/data/batch_metrics_enabled.conf': java.nio.file.NoSuchFileException: /usr/share/opensearch/data/batch_metrics_enabled.conf
Dec 31, 2022 11:18:57 AM org.jooq.tools.JooqLogger info
INFO: 
                                      
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@  @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@        @@@@@@@@@@
@@@@@@@@@@@@@@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@  @@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@        @@  @  @  @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@  @@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  Thank you for using jOOQ 3.10.8
                                      
11:18:57.402 [pa-reader] ERROR org.opensearch.performanceanalyzer.reader.ReaderMetricsProcessor - Error reading file '/usr/share/opensearch/data/batch_metrics_enabled.conf': java.nio.file.NoSuchFileException: /usr/share/opensearch/data/batch_metrics_enabled.conf
11:18:59.554 [pa-reader] ERROR org.opensearch.performanceanalyzer.reader.ReaderMetricsProcessor - Error reading file '/usr/share/opensearch/data/batch_metrics_enabled.conf': java.nio.file.NoSuchFileException: /usr/share/opensearch/data/batch_metrics_enabled.conf
Dec 31, 2022 11:19:02 AM org.jooq.tools.JooqLogger info
INFO: Single batch             : No bind variables have been provided with a single statement batch execution. This may be due to accidental API misuse
```

**Host/Environment (please complete the following information):**
 - OS: Windows+WSL2 or Ubuntu 22.10
 - Version: reproduced on opensearch 2.3.0 or 2.4.1

**Additional context**
Opened an issue for some other logs: https://github.com/opensearch-project/performance-analyzer/issues/355

**Comment by bbarani** [comment]
[Triage] We will look in this issue and update our findings soon. CC: @prudhvigodithi

**Comment by prudhvigodithi** [comment]
Hey I'm able to re-produce this with docker installation (in both 1.x and 2.x) and not with tar installation, I suspect this is because of how the PA plugin is started as [recommend](https://opensearch.org/docs/latest/monitoring-plugins/pa/index/#install-performance-analyzer) and as seen in the [entrypoint](https://github.com/opensearch-project/opensearch-build/blob/main/docker/release/config/opensearch/opensearch-docker-entrypoint.sh#LL61C66-L61C96), but inside docker i can see both files `batch_metrics_enabled.conf` `rca_enabled.conf`. 
@peterzhuamazon

**Comment by peterzhuamazon** [comment]
As for both the TAR and DOCKER it is missing a few lines that rpm has:
```
echo 'true' > ${data_dir}/rca_enabled.conf
echo 'true' > ${config_dir}/performance_analyzer_enabled.conf
echo 'true' > ${config_dir}/rca_enabled.conf
```

Rest are the same in TAR/DOCKER/RPM.

**Comment by peterzhuamazon** [comment]
I will tweak the issues coming from install_tar script.

**Comment by peterzhuamazon** [comment]
Update seems like all the configs only take effect in data folder.
https://github.com/opensearch-project/performance-analyzer/blob/6600a14899c00c7229ec7be79c034297f8577bac/src/main/java/org/opensearch/performanceanalyzer/config/PerformanceAnalyzerController.java#L28-L36

And seems like the missing error is fine as user can just add a config if needed.

Will let the performance analyzer team confirm. Thanks.

**Comment by peterzhuamazon** [comment]
PA team confirms these details here:

```
 These config files (performance_analyzer_enabled.conf) should be present in the data folder and not in either $OPENSEARCH_HOME/config or are they existing in $OPENSEARCH_HOME/config/opensearch-performance-analyzer

We can ignore the logs for now as batch_metrics will not affect other functionalities. I assume this happens only during startup. After both the process and plugin come up and if the file is still missing, we create this file with default value. If thats not case and we are seeing errors after long time, we should address the issue and create this file with default value.
```

Basically at startup if the files not present, it will error once but will auto create the file based on the defined default value.

We only explicitly enable it on RPM before is because they are not like TAR which is meant for easier installation and usages. On TAR user can choose to manually create the file on currently released versions at the time of the writing and restart the cluster.
