### ISSUE TITLE
[Bug]: src/system/os.py does not correctly return architecture for bsd platform

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#3236]
### Describe the bug

Run `uname -m` will return follow in the freebsd:
```
amd64
```

The code here does not support `amd64` as input:
https://github.com/opensearch-project/opensearch-build/blob/main/src/system/os.py#L12-L19
```
def current_architecture() -> str:
    architecture = subprocess.check_output(["uname", "-m"]).decode().strip()
    if architecture == "x86_64":
        return "x64"
    elif architecture == "aarch64" or architecture == "arm64":
        return "arm64"
    else:
        raise ValueError(f"Unsupported architecture: {architecture}")
```

Thanks.

### To reproduce

Run the build process on a freebsd server and see output:
```
$ ./build.sh manifests/2.4.0/opensearch-2.4.0.yml --component OpenSearch
Installing dependencies in . ...
Installing dependencies from Pipfile.lock (b36c9c)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Running ./src/run_build.py manifests/2.4.0/opensearch-2.4.0.yml --component OpenSearch ...
2023-02-23 23:15:47 INFO     Building in /tmp/tmpllimwxjs
2023-02-23 23:15:47 INFO     Removing /tmp/tmpllimwxjs
Traceback (most recent call last):
  File "./src/run_build.py", line 81, in <module>
    sys.exit(main())
  File "./src/run_build.py", line 55, in main
    architecture=args.architecture or manifest.build.architecture,
  File "/usr/share/opensearch/opensearch-build/src/build_workflow/build_target.py", line 45, in __init__
    self.architecture = architecture or current_architecture()
  File "/usr/share/opensearch/opensearch-build/src/system/os.py", line 20, in current_architecture
    raise ValueError(f"Unsupported architecture: {architecture}")
ValueError: Unsupported architecture: amd64

```

### Expected behavior

The bsd x64 hosts can run the code without specifying --architecture x64.

**Comment by jordarlu** [comment]
Hello, @peterzhuamazon ...as you have the PR merged, do you think we can close this issue? Thanks !!

**Comment by peterzhuamazon** [comment]
Closing now.
