### ISSUE TITLE
Opensearch: [Segment Replication] Add new Test manifest to test all plugin compatibility with Segment Replication enabled.

### ISSUE THREAD

**Issue by Rishikesh1159** [opensearch-project/opensearch-build#3345]
### Is your feature request related to a problem? Please describe

Coming from: https://github.com/opensearch-project/OpenSearch/issues/6602

Leading up to GA of segment replication in opensearch 2.7, we need to do a round of sanity testing with plugins.

To do this testing we need a new test-manifest exactly same as https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.7.0/opensearch-2.7.0-test.yml but with below values added to each plugin:

```
additional-cluster-configs:
   opensearch.experimental.feature.replication_type.enabled: true
   cluster.indices.replication.strategy: "SEGMENT"
```

### Describe the solution you'd like
 To enable segment replication by default, we need to set feature flag and a cluster setting. Both of these must be passed/set from opensearch.yml

-> To enable segment replication feature flag, we have to pass: 
`opensearch.experimental.feature.replication_type.enabled: true` in opensearch.yml. ([4959](https://github.com/opensearch-project/OpenSearch/pull/4959)).
-> To set cluster setting of replication type, we have to pass: `cluster.indices.replication.strategy: "SEGMENT"` in opensearch.yml. ([6791](https://github.com/opensearch-project/OpenSearch/pull/6791)).

**Comment by gaiksaya** [comment]
Hi @Rishikesh1159,

I believe we want to keep the actual integration testing separate from seg-Rep feature testing.
We can add one more test-manifest exactly same as https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.7.0/opensearch-2.7.0-test.yml but with below values added to each plugin:

```yml
additional-cluster-configs:
   opensearch.experimental.feature.replication_type.enabled: true
   cluster.indices.replication.strategy: "SEGMENT"
```

This will add above values to opensearch.yml to each cluster that is deployed for testing. 
cc: @bbarani

**Comment by Rishikesh1159** [comment]
Hi @gaiksaya, yes you are correct. Sorry for confusing description, the request here is to add those values to opensearch.yml. Let me change the description of this issue to make it clear

**Comment by gaiksaya** [comment]
Thanks! So I tried adding the running with above configuration and looks like cluster is unable to start. 
<details><summary>Error</summary>
<p>

```
[2023-03-23T15:56:40,947][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [node_name_9200] uncaught exception in thread [main]
org.opensearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [cluster.indices.replication.strategy] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:184) ~[opensearch-2.7.0.jar:2.7.0]
	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:171) ~[opensearch-2.7.0.jar:2.7.0]
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104) ~[opensearch-2.7.0.jar:2.7.0]
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) ~[opensearch-cli-2.7.0.jar:2.7.0]
	at org.opensearch.cli.Command.main(Command.java:101) ~[opensearch-cli-2.7.0.jar:2.7.0]
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:137) ~[opensearch-2.7.0.jar:2.7.0]
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:103) ~[opensearch-2.7.0.jar:2.7.0]
Caused by: java.lang.IllegalArgumentException: unknown setting [cluster.indices.replication.strategy] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
	at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:608) ~[opensearch-2.7.0.jar:2.7.0]
	at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:549) ~[opensearch-2.7.0.jar:2.7.0]
	at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:519) ~[opensearch-2.7.0.jar:2.7.0]
	at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:489) ~[opensearch-2.7.0.jar:2.7.0]
	at org.opensearch.common.settings.SettingsModule.<init>(SettingsModule.java:179) ~[opensearch-2.7.0.jar:2.7.0]
	at org.opensearch.node.Node.<init>(Node.java:514) ~[opensearch-2.7.0.jar:2.7.0]
	at org.opensearch.node.Node.<init>(Node.java:361) ~[opensearch-2.7.0.jar:2.7.0]
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-2.7.0.jar:2.7.0]
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-2.7.0.jar:2.7.0]
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404) ~[opensearch-2.7.0.jar:2.7.0]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180) ~[opensearch-2.7.0.jar:2.7.0]
	... 6 more

```

</p>
</details> 

Steps to replicate:

1. Clone [opensearch-build](https://github.com/opensearch-project/opensearch-build) repository
2. Get the last successful build that you want to run integration test against from https://build.ci.opensearch.org/job/distribution-build-opensearch/
3. Run below command:
```
./test.sh integ-test manifests/2.7.0/opensearch-2.7.0-test-segRep.yml --component ml-commons --test-run-id 3455 -p opensearch=https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.7.0/7320/linux/x64/tar --keep
```
Make sure you pas `--keep` to keep the temp folders to check logs

**Comment by Rishikesh1159** [comment]
Thanks @gaiksaya for detailed info on steps to reproduce. Looks like my changes are not present in build [7320](https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.7.0/7320/linux/x64/tar build). My changes merged to 2.x branch after this build. So, inorder to set this cluster setting we need a new successful build. Currently the latest successful build for 2.7 is still [7320](https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.7.0/7320/linux/x64/tar build), so we need to wait until new successful build of 2.7 branch happens

**Comment by gaiksaya** [comment]
Triggered a new build: https://build.ci.opensearch.org/job/distribution-build-opensearch/7325/

**Comment by gaiksaya** [comment]
Triggered a test with segment replication enabled https://build.ci.opensearch.org/blue/organizations/jenkins/integ-test/detail/integ-test/3979/pipeline
