### ISSUE TITLE
[Bug]: Published core lib are desynced with snapshots and break plugin builds

### ISSUE THREAD

**Issue by Yury-Fridlyand** [opensearch-project/opensearch-build#3449]
### Describe the bug

https://github.com/opensearch-project/OpenSearch/pull/7306 and https://github.com/opensearch-project/OpenSearch/pull/7165 (and number of other changes before) causes major changes in core libraries. I don't know entire workflow of publishing snapshots, but it takes much more time than publish core libs. The delay could be up to 1 week. Along this time, no plugin code could be compiled/tested because core libs and snapshots are not in sync. All development is paralyzed.

### To reproduce

^

### Expected behavior

Stash newer core libs before publish until snapshot is ready. Publish both together only.

### Relevant log output

```shell
fatal error in thread [opensearch[Matthew-Ws-MacBook-Pro.local][sql-worker][T#1]], exiting
java.lang.NoSuchMethodError: 'java.util.Map org.opensearch.action.admin.indices.mapping.get.GetMappingsResponse.mappings()'
	at org.opensearch.sql.opensearch.client.OpenSearchNodeClient.getIndexMappings(OpenSearchNodeClient.java:91) ~[?:?]
	at org.opensearch.sql.opensearch.request.system.OpenSearchDescribeIndexRequest.getFieldTypes(OpenSearchDescribeIndexRequest.java:85) ~[?:?]
	at org.opensearch.sql.opensearch.storage.OpenSearchIndex.getFieldTypes(OpenSearchIndex.java:117) ~[?:?]
	at org.opensearch.sql.analysis.Analyzer.visitRelation(Analyzer.java:156) ~[?:?]
	at org.opensearch.sql.analysis.Analyzer.visitRelation(Analyzer.java:106) ~[?:?]
	at org.opensearch.sql.ast.tree.Relation.accept(Relation.java:98) ~[?:?]
	at org.opensearch.sql.analysis.Analyzer.visitProject(Analyzer.java:365) ~[?:?]
	at org.opensearch.sql.analysis.Analyzer.visitProject(Analyzer.java:106) ~[?:?]
	at org.opensearch.sql.ast.tree.Project.accept(Project.java:71) ~[?:?]
	at org.opensearch.sql.analysis.Analyzer.analyze(Analyzer.java:133) ~[?:?]
	at org.opensearch.sql.executor.QueryService.analyze(QueryService.java:93) ~[?:?]
	at org.opensearch.sql.executor.QueryService.execute(QueryService.java:43) ~[?:?]
	at org.opensearch.sql.executor.execution.QueryPlan.execute(QueryPlan.java:50) ~[?:?]
	at org.opensearch.sql.opensearch.executor.OpenSearchQueryManager.lambda$submit$0(OpenSearchQueryManager.java:33) ~[?:?]
	at org.opensearch.sql.opensearch.executor.OpenSearchQueryManager.lambda$withCurrentContext$1(OpenSearchQueryManager.java:47) ~[?:?]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:747) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) [?:?]
fatal error in thread [opensearch[Matthew-Ws-MacBook-Pro.local][sql-worker][T#1]], exiting
java.lang.NoSuchMethodError: 'java.util.Map org.opensearch.action.admin.indices.mapping.get.GetMappingsResponse.mappings()'
	at org.opensearch.sql.opensearch.client.OpenSearchNodeClient.getIndexMappings(OpenSearchNodeClient.java:91)
	at org.opensearch.sql.opensearch.request.system.OpenSearchDescribeIndexRequest.getFieldTypes(OpenSearchDescribeIndexRequest.java:85)
	at org.opensearch.sql.opensearch.storage.OpenSearchIndex.getFieldTypes(OpenSearchIndex.java:117)
	at org.opensearch.sql.analysis.Analyzer.visitRelation(Analyzer.java:156)
	at org.opensearch.sql.analysis.Analyzer.visitRelation(Analyzer.java:106)
	at org.opensearch.sql.ast.tree.Relation.accept(Relation.java:98)
	at org.opensearch.sql.analysis.Analyzer.visitProject(Analyzer.java:365)
	at org.opensearch.sql.analysis.Analyzer.visitProject(Analyzer.java:106)
	at org.opensearch.sql.ast.tree.Project.accept(Project.java:71)
	at org.opensearch.sql.analysis.Analyzer.analyze(Analyzer.java:133)
	at org.opensearch.sql.executor.QueryService.analyze(QueryService.java:93)
	at org.opensearch.sql.executor.QueryService.execute(QueryService.java:43)
	at org.opensearch.sql.executor.execution.QueryPlan.execute(QueryPlan.java:50)
	at org.opensearch.sql.opensearch.executor.OpenSearchQueryManager.lambda$submit$0(OpenSearchQueryManager.java:33)
	at org.opensearch.sql.opensearch.executor.OpenSearchQueryManager.lambda$withCurrentContext$1(OpenSearchQueryManager.java:47)
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:747)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
```
```

**Comment by nknize** [comment]
This is a big reason for the refactor of these core classes out of `:server` into the `:libs` and to decouple this mess of a plugin framework from the server logic. Downstream shouldn't be so dependent on the fat build. We'll get there. In the meantime there will be some growing pains like this.
