### ISSUE TITLE
[Bug]: Current integ tests workflow fails on version incompatibility

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/opensearch-build#3554]
### Describe the bug

The current OS integ tests fails on importing module because `urllib` only supports `OpenSSL` 1.1.1+. Current ssl version is `1.0.2`

Link: https://build.ci.opensearch.org/blue/organizations/jenkins/integ-test/detail/integ-test/4980/pipeline/74
Full context: 
```
Running ./src/run_integ_test.py manifests/2.8.0/opensearch-2.8.0-test.yml --component job-scheduler --test-run-id 4980 --paths opensearch=/var/jenkins/workspace/integ-test/tar --base-path https://ci.opensearch.org/ci/dbc/integ-test/2.8.0/7879/linux/x64/tar ...

Traceback (most recent call last):

  File "./src/run_integ_test.py", line 13, in <module>

    from test_workflow.integ_test.integ_test_runners import IntegTestRunners

  File "/var/jenkins/workspace/integ-test/src/test_workflow/integ_test/integ_test_runners.py", line 11, in <module>

    from test_workflow.integ_test.integ_test_runner_opensearch import IntegTestRunnerOpenSearch

  File "/var/jenkins/workspace/integ-test/src/test_workflow/integ_test/integ_test_runner_opensearch.py", line 15, in <module>

    from test_workflow.integ_test.integ_test_suite_opensearch import IntegTestSuiteOpenSearch

  File "/var/jenkins/workspace/integ-test/src/test_workflow/integ_test/integ_test_suite_opensearch.py", line 22, in <module>

    from test_workflow.integ_test.topology import NodeEndpoint, Topology

  File "/var/jenkins/workspace/integ-test/src/test_workflow/integ_test/topology.py", line 16, in <module>

    from test_workflow.integ_test.local_test_cluster import LocalTestCluster

  File "/var/jenkins/workspace/integ-test/src/test_workflow/integ_test/local_test_cluster.py", line 13, in <module>

    from test_workflow.integ_test.service import Service

  File "/var/jenkins/workspace/integ-test/src/test_workflow/integ_test/service.py", line 14, in <module>

    import requests

  File "/usr/share/opensearch/.local/share/virtualenvs/integ-test-B5RGX0jA/lib/python3.7/site-packages/requests/__init__.py", line 43, in <module>

    import urllib3

  File "/usr/share/opensearch/.local/share/virtualenvs/integ-test-B5RGX0jA/lib/python3.7/site-packages/urllib3/__init__.py", line 39, in <module>

    "urllib3 v2.0 only supports OpenSSL 1.1.1+, currently "

ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2k-fips  26 Jan 2017. See: https://github.com/urllib3/urllib3/issues/2168

script returned exit code 1
```

### To reproduce

https://build.ci.opensearch.org/blue/organizations/jenkins/integ-test/detail/integ-test/4980/pipeline/74

**Comment by peterzhuamazon** [comment]
This seems like an upgrade on urllib3 libs due to not supporting openssl version lower than 1.1.1+, where centos7 does not have now. We would need to speed up the process to upgrade to rockylinux8.

**Comment by zelinh** [comment]
This might be helpful. https://urllib3.readthedocs.io/en/latest/v2-migration-guide.html#common-upgrading-issues

**Comment by peterzhuamazon** [comment]
Related to this:
* https://github.com/opensearch-project/opensearch-build/commit/a20ba9724bbf29a3909593e2b265b0834d680fb4

**Comment by peterzhuamazon** [comment]
The newer version of requests cause a requirement update on openssl, from 1.1.0 to 1.1.1+, this means CentOS7 is not able to run newer version of request on any activities related to our python code.

**Comment by peterzhuamazon** [comment]
Hi,

Option 1: Revert #3544 and keep using CentOS7 for this release
Option 2: Move all the changes to RockyLinux8 and remove CentOS7 support.

Consider our decision on the AL2023/NodeJS18/PythonUpgrade 3.9 has already made in this comment:https://github.com/opensearch-project/opensearch-build/issues/1563#issuecomment-1560119519

We will go ahead with option 1 and revert #3544.

cc: @bbarani @gaiksaya 

Thanks.

**Comment by peterzhuamazon** [comment]
Our test in #3544 is running in ubuntu-latest thus does not have the openssl issue in centos7, therefore, not caught.
