### ISSUE TITLE
[BUG] Snapshot bundle cannot be assembled

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#359]
**Describe the bug**

OpenSearch doesn't support installing builds that declare -SNAPSHOT in plugin descriptor. Assembly fails with `java.lang.IllegalArgumentException: illegal version format - snapshot labels are not supported`.

**To Reproduce**

```
./bundle-workflow/build.sh manifests/opensearch-1.1.0.yml --snapshot
./bundle-workflow/assemble.sh manifests/opensearch-1.1.0.yml

-> Installing file:/tmp/tmpe_np2do4/opensearch-security-1.1.0.0-SNAPSHOT.zip
-> Downloading file:/tmp/tmpe_np2do4/opensearch-security-1.1.0.0-SNAPSHOT.zip
-> Failed installing file:/tmp/tmpe_np2do4/opensearch-security-1.1.0.0-SNAPSHOT.zip
-> Rolling back file:/tmp/tmpe_np2do4/opensearch-security-1.1.0.0-SNAPSHOT.zip
-> Rolled back file:/tmp/tmpe_np2do4/opensearch-security-1.1.0.0-SNAPSHOT.zip
Exception in thread "main" java.lang.IllegalArgumentException: illegal version format - snapshot labels are not supported
        at org.opensearch.Version.fromStringSlow(Version.java:177)
        at org.opensearch.Version.fromString(Version.java:172)
        at org.opensearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:212)
        at org.opensearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:799)
        at org.opensearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:858)
        at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:263)
        at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:237)
        at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:99)
        at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:140)
        at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
        at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:140)
        at org.opensearch.cli.Command.main(Command.java:103)
        at org.opensearch.plugins.PluginCli.main(PluginCli.java:60)
```

**Expected behavior**

Not sure. Do we need to assemble a snapshot bundle? Probably not.

**Additional Context**

https://github.com/opensearch-project/OpenSearch/blob/19e54d662488a183c1388e66cfe7463a24c6aa7c/buildSrc/src/main/resources/plugin-descriptor.properties#L48 says that the version of `opensearch.version` is the one built against.

**Comment by dblock** [comment]
@nknize What was the original intent of this limitation? Feels like we must be doing something wrong.
