### ISSUE TITLE
[Bug]: Base path parameter is not supported in BWC test workflow

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/opensearch-build#3913]
### Describe the bug

We added a new `base-path` parameter to our test recorder in order to generate the component yaml file to keep track of the test logs. https://github.com/opensearch-project/opensearch-build/pull/3497
With a new argument to initiate the test-recorder, we would be able to access all of those logs created from the test workflow. 

However, it looks like it's not added to support our BWC test workflow. 
The current error index: 
```
Traceback (most recent call last):
  File "/var/jenkins/workspace/bwc-test/./src/run_bwc_test.py", line 36, in <module>
    sys.exit(main())
  File "/var/jenkins/workspace/bwc-test/./src/run_bwc_test.py", line 25, in main
    all_results = BwcTestRunners.from_test_manifest(args, test_manifest).run()
  File "/var/jenkins/workspace/bwc-test/src/test_workflow/bwc_test/bwc_test_runner.py", line 46, in run
    test_results = test_suite.execute_tests()
  File "/var/jenkins/workspace/bwc-test/src/test_workflow/bwc_test/bwc_test_suite.py", line 63, in execute_tests
    status = self.execute_bwctest_sh(config)
  File "/var/jenkins/workspace/bwc-test/src/test_workflow/bwc_test/bwc_test_suite.py", line 87, in execute_bwctest_sh
    self.save_logs.save_test_result_data(test_result_data)
  File "/var/jenkins/workspace/bwc-test/src/test_workflow/test_recorder/test_recorder.py", line 145, in save_test_result_data
    self.parent_class._generate_yml(test_result_data, dest_directory)
  File "/var/jenkins/workspace/bwc-test/src/test_workflow/test_recorder/test_recorder.py", line 58, in _generate_yml
    base_file_path = self._get_file_path(self.base_path, test_result_data.component_name, test_result_data.component_test_config)
  File "/var/jenkins/workspace/bwc-test/src/test_workflow/test_recorder/test_recorder.py", line 40, in _get_file_path
    if base_path.startswith("https://"):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

### To reproduce

Run
```
./test.sh bwc-test manifests/2.10.0/opensearch-2.10.0-test.yml --test-run-id 4103 --paths opensearch=https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.10.0/8271/linux/x64/tar
``` 
within our test container `public.ecr.aws/opensearchstaging/ci-runner:ci-runner-centos7-opensearch-build-v3`

**Comment by zelinh** [comment]
The recent BWC test passed on x64 distribution. 
https://build.ci.opensearch.org/job/bwc-test/4113/console

Closing this issue for now.
