### ISSUE TITLE
[BUG] Performance Analyzer is missing policy

### ISSUE THREAD

**Issue by user29835461** [opensearch-project/opensearch-build#3945]
Installation of 2.6.0 from rpm distribution, trying to enable Performance Analyzer plugin will not start and throws

```
[2023-08-31T10:54:17,988][ERROR][o.o.p.o.OSGlobals        ] [omlogdata01] Error in static initialization of OSGlobals with exception: java.security.AccessControlException: access denied ("java.io.FilePermission" "/proc/self/task" "read")
java.security.AccessControlException: access denied ("java.io.FilePermission" "/proc/self/task" "read")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:485) ~[?:?]
        at java.security.AccessController.checkPermission(AccessController.java:1068) ~[?:?]
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:416) ~[?:?]
        at java.lang.SecurityManager.checkRead(SecurityManager.java:756) ~[?:?]
        at java.io.File.normalizedList(File.java:1171) ~[?:?]
        at java.io.File.listFiles(File.java:1269) ~[?:?]
        at org.opensearch.performanceanalyzer.os.OSGlobals.enumTids(OSGlobals.java:75) ~[performanceanalyzer-rca-2.6.0.0.jar:?]
```

This happens because the [security policy ](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/resources/org/opensearch/bootstrap/security.policy) for opensearch is missing the required access right:

```
# Example
grant {
    permission java.io.FilePermission "/proc/self/task", "read";
};
```

I tested this by injecting a separate extra policy file by JVM option `-Djava.security.policy=file:///etc/opensearch/mycustompolicy.policy`  and it makes the issue go away.

**Comment by jordarlu** [comment]
Thanks for reporting an issue you faced, @user29835461
I may need a bit more info from you to reproduce it on my end becasue I was able to enable it per the instruction at [here](https://opensearch.org/docs/2.6/monitoring-your-cluster/pa/index/), maybe you could share the exact steps and commands you took? thanks!

**Comment by peterzhuamazon** [comment]
We are definitely not seeing issues on our end on CentOS/RockyLinux/AmazonLinux.

@user29835461 Would you mind provide more information on your system and how to reproduce it on your end?

Thanks.

**Comment by gaiksaya** [comment]
closing this issue as there is no response from the author since a month.
Please re-open if you need help.

Thanks!
