### ISSUE TITLE
Report workflow hard fails if component doesn't have certain test type

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/opensearch-build#4042]
### Is your feature request related to a problem? Please describe

Error context:
```
Running ./src/run_test_report.py manifests/1.3.13/opensearch-dashboards-1.3.13-test.yml --artifact-paths opensearch=https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.13/8499/linux/x64/tar opensearch-dashboards=https://ci.opensearch.org/ci/dbc/distribution-build-opensearch-dashboards/1.3.13/6598/linux/x64/tar --test-run-id 4096 --test-type integ-test --base-path https://ci.opensearch.org/ci/dbc/integ-test-opensearch-dashboards/1.3.13/6598/linux/x64/tar ...
2023-09-19 00:45:40 INFO     Loading manifests/1.3.13/opensearch-dashboards-1.3.13-test.yml
2023-09-19 00:45:40 INFO     ./test.sh integ-test manifests/1.3.13/opensearch-dashboards-1.3.13-test.yml --paths opensearch=https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.13/8499/linux/x64/tar opensearch-dashboards=https://ci.opensearch.org/ci/dbc/distribution-build-opensearch-dashboards/1.3.13/6598/linux/x64/tar
2023-09-19 00:45:40 INFO     ./test.sh integ-test manifests/1.3.13/opensearch-dashboards-1.3.13-test.yml --paths opensearch=https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.13/8499/linux/x64/tar opensearch-dashboards=https://ci.opensearch.org/ci/dbc/distribution-build-opensearch-dashboards/1.3.13/6598/linux/x64/tar --component OpenSearch-Dashboards
Traceback (most recent call last):
  File "/var/jenkins/workspace/integ-test-opensearch-dashboards@2/./src/run_test_report.py", line 34, in <module>
    sys.exit(main())
  File "/var/jenkins/workspace/integ-test-opensearch-dashboards@2/./src/run_test_report.py", line 26, in main
    test_report_data = test_report_runner.update_data()
  File "/var/jenkins/workspace/integ-test-opensearch-dashboards@2/src/report_workflow/test_report_runner.py", line 52, in update_data
    self.test_run_data["components"].append(self.component_entry(component.name))
  File "/var/jenkins/workspace/integ-test-opensearch-dashboards@2/src/report_workflow/test_report_runner.py", line 78, in component_entry
    config_names = [config for config in test_component.__to_dict__().get(self.test_type)["test-configs"]]
TypeError: 'NoneType' object is not subscriptable
```

The reason of this issue is that for 1.3.13 dashboards test manifest. We don't have `integ-test` entry for OpenSearch-Dashboards components. 

### Describe the solution you'd like

If we don't specify certain test type for one component, the workflow should just skip this component and continue on the rest of them.

**Comment by zelinh** [comment]
This issue can be reproduced locally if we revert the temp changes #4044 with:
```
./report.sh manifests/1.3.13/opensearch-dashboards-1.3.13-test.yml --artifact-paths opensearch=https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.13/8499/linux/x64/tar opensearch-dashboards=https://ci.opensearch.org/ci/dbc/distribution-build-opensearch-dashboards/1.3.13/6598/linux/x64/tar --test-run-id 4096 --test-type integ-test --base-path https://ci.opensearch.org/ci/dbc/integ-test-opensearch-dashboards/1.3.13/6598/linux/x64/tar
```

**Comment by zelinh** [comment]
Closing this issue as it's fixed now.
