### ISSUE TITLE
[Bug]: Validation run for OpenSearch Dashboard fails with unauthorized error

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#4442]
### Describe the bug

Tried running validation workflow for 2.3.0. It passed for OpenSearch but failed for Dashboards with below error:

```
2024-02-11 16:26:36 INFO
Status_code ->401
response_text ->
/home/gaiksaya/.local/share/virtualenvs/opensearch-build-Jk4AL_lu/lib/python3.7/site-packages/urllib3/connectionpool.py:1068: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
2024-02-11 16:26:37 INFO
Request_url ->https://localhost:9200/_cat/health?v

2024-02-11 16:26:37 INFO
Status_code ->401
response_text ->
2024-02-11 16:26:37 INFO
Request_url ->http://localhost:5601/api/status

2024-02-11 16:26:37 INFO
Status_code ->401
response_text ->{"statusCode":401,"error":"Unauthorized","message":"Authentication Exception"}
Traceback (most recent call last):
  File "/local/home/gaiksaya/opensearch-build/src/validation_workflow/validation.py", line 52, in run
    return self.download_artifacts() and self.installation() and self.start_cluster() and self.validation() and self.cleanup()
  File "/local/home/gaiksaya/opensearch-build/src/validation_workflow/tar/validation_tar.py", line 75, in validation
    raise Exception(f'Not all tests Pass : {counter}')
Exception: Not all tests Pass : There are 0/4 test cases Pass

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./src/run_validation.py", line 28, in <module>
    sys.exit(main())
  File "./src/run_validation.py", line 22, in main
    test_result = ValidationTestRunner.dispatch(args, args.distribution).run()
  File "/local/home/gaiksaya/opensearch-build/src/validation_workflow/validation.py", line 54, in run
    raise Exception(f'An error occurred while running the validation tests: {str(e)}')
Exception: An error occurred while running the validation tests: Not all tests Pass : There are 0/4 test cases Pass
```

### To reproduce

Run the below command:

```
./validation.sh --file-path opensearch=https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.3.0/latest/linux/x64/tar/dist/opensearch/opensearch-2.3.0-linux-x64.tar.gz opensearch-dashboards=https://ci.opensearch.org/ci/dbc/distribution-build-opensearch-dashboards/2.3.0/latest/linux/x64/tar/dist/opensearch-dashboards/opensearch-dashboards-2.3.0-linux-x64.tar.gz
```

### Expected behavior

Validation should go through as 2.3.0 latest artifacts are valid.

**Comment by rishabh6788** [comment]
@Divyaasm Please confirm the issue and update your findings.

**Comment by peterzhuamazon** [comment]
@Divyaasm confirms she will take case of the task.

**Comment by jordarlu** [comment]
Hi, @Divyaasm, do you think we can close this issue as your PR has been merged? Thank you!
