### ISSUE TITLE
[BUG] Autocut tickets incorrectly cut to plugins

### ISSUE THREAD

**Issue by jmazanec15** [opensearch-project/opensearch-build#4606]
## Description

For https://github.com/opensearch-project/k-NN/issues/1591, I went to https://build.ci.opensearch.org/blue/organizations/jenkins/distribution-build-opensearch/detail/distribution-build-opensearch/9674/pipeline and looked at a failing workload and see:
```
2024-04-04 02:05:00 ERROR    Failed plugins are ['k-NN', 'skills']
```

but in the build it doesnt look like k-NN failed - but AD failed:
```
/tmp/tmpsdy18vrx/skills/src/main/java/org/opensearch/agent/tools/SearchAnomalyDetectorsTool.java:68: error: cannot find symbol

    private AnomalyDetectionNodeClient adClient;

            ^

  symbol:   class AnomalyDetectionNodeClient

  location: class org.opensearch.agent.tools.SearchAnomalyDetectorsTool

/tmp/tmpsdy18vrx/skills/src/main/java/org/opensearch/agent/tools/SearchAnomalyDetectorsTool.java:281: error: cannot find symbol

        private AnomalyDetectionNodeClient adClient;

                ^

  symbol:   class AnomalyDetectionNodeClient

  location: class org.opensearch.agent.tools.SearchAnomalyDetectorsTool.Factory

/tmp/tmpsdy18vrx/skills/src/main/java/org/opensearch/agent/tools/SearchAnomalyResultsTool.java:15: error: package org.opensearch.ad.client does not exist

import org.opensearch.ad.client.AnomalyDetectionNodeClient;

                               ^

/tmp/tmpsdy18vrx/skills/src/main/java/org/opensearch/agent/tools/SearchAnomalyResultsTool.java:58: error: cannot find symbol

    private AnomalyDetectionNodeClient adClient;

            ^

  symbol:   class AnomalyDetectionNodeClient

  location: class org.opensearch.agent.tools.SearchAnomalyResultsTool

/tmp/tmpsdy18vrx/skills/src/main/java/org/opensearch/agent/tools/SearchAnomalyResultsTool.java:196: error: cannot find symbol

        private AnomalyDetectionNodeClient adClient;

                ^

  symbol:   class AnomalyDetectionNodeClient

  location: class org.opensearch.agent.tools.SearchAnomalyResultsTool.Factory


> Task :compileJava

/tmp/tmpsdy18vrx/skills/src/main/java/org/opensearch/agent/tools/SearchMonitorsTool.java:55: warning: Not generating getType(): A method with that name already exists

    @Getter

    ^

/tmp/tmpsdy18vrx/skills/src/main/java/org/opensearch/agent/tools/SearchAlertsTool.java:44: warning: Not generating getType(): A method with that name already exists

    @Getter

    ^

/tmp/tmpsdy18vrx/skills/src/main/java/org/opensearch/agent/tools/PPLTool.java:81: warning: Not generating getName(): A method with that name already exists

    @Getter

    ^

/tmp/tmpsdy18vrx/skills/src/main/java/org/opensearch/agent/tools/SearchAnomalyDetectorsTool.java:21: error: package org.opensearch.ad.client does not exist

import org.opensearch.ad.client.AnomalyDetectionNodeClient;

                               ^

/tmp/tmpsdy18vrx/skills/src/main/java/org/opensearch/agent/tools/SearchAnomalyDetectorsTool.java:22: error: package org.opensearch.ad.model does not exist

import org.opensearch.ad.model.ADTask;

                              ^

/tmp/tmpsdy18vrx/skills/src/main/java/org/opensearch/agent/tools/SearchAnomalyDetectorsTool.java:23: error: package org.opensearch.ad.transport does not exist

import org.opensearch.ad.transport.GetAnomalyDetectorRequest;

                                  ^

/tmp/tmpsdy18vrx/skills/src/main/java/org/opensearch/agent/tools/SearchAnomalyDetectorsTool.java:24: error: package org.opensearch.ad.transport does not exist

import org.opensearch.ad.transport.GetAnomalyDetectorResponse;

                                  ^

/tmp/tmpsdy18vrx/skills/src/main/java/org/opensearch/agent/tools/SearchAnomalyDetectorsTool.java:68: error: cannot find symbol

    private AnomalyDetectionNodeClient adClient;

            ^

  symbol:   class AnomalyDetectionNodeClient

  location: class SearchAnomalyDetectorsTool

/tmp/tmpsdy18vrx/skills/src/main/java/org/opensearch/agent/tools/SearchAnomalyDetectorsTool.java:281: error: cannot find symbol

        private AnomalyDetectionNodeClient adClient;

                ^

  symbol:   class AnomalyDetectionNodeClient

  location: class Factory

/tmp/tmpsdy18vrx/skills/src/main/java/org/opensearch/agent/tools/SearchAnomalyResultsTool.java:15: error: package org.opensearch.ad.client does not exist

import org.opensearch.ad.client.AnomalyDetectionNodeClient;

                               ^

/tmp/tmpsdy18vrx/skills/src/main/java/org/opensearch/agent/tools/SearchAnomalyResultsTool.java:58: error: cannot find symbol

    private AnomalyDetectionNodeClient adClient;

            ^

  symbol:   class AnomalyDetectionNodeClient

  location: class SearchAnomalyResultsTool

/tmp/tmpsdy18vrx/skills/src/main/java/org/opensearch/agent/tools/SearchAnomalyResultsTool.java:196: error: cannot find symbol

        private AnomalyDetectionNodeClient adClient;

                ^

  symbol:   class AnomalyDetectionNodeClient

  location: class Factory

Note: /tmp/tmpsdy18vrx/skills/src/main/java/org/opensearch/agent/tools/RAGTool.java uses or overrides a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

9 errors

3 warnings


> Task :compileJava FAILED


FAILURE: Build failed with an exception.


* What went wrong:

Execution failed for task ':compileJava'.

> Compilation failed; see the compiler error output for details.


* Try:

> Run with --scan to get full insights.


* Exception is:

org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compileJava'.

	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:148)

	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)

	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:146)

	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:134)

	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)

	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)

	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)

	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:74)

	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)

	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)

	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)

	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)

	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)

	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)

	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)

	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)

	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)

	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)

	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)

	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:78)

```

## Solution I would like to see
From the logs, I cannot find anywhere the failure for k-NN - so I dont think the issue should be cut. Additionally, for the autocut tickets, it would be helpful to have the failure message in the body of the issue so that it can be triaged faster.

**Comment by jmazanec15** [comment]
closing - @bbarani found in https://github.com/opensearch-project/k-NN/issues/1591#issuecomment-2038066893
