### ISSUE TITLE
yaml-lint failure on pipenv install step

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#4767]
https://github.com/opensearch-project/opensearch-build/actions/runs/9487703240/job/26145880300?pr=4765

```
Run python -m pip install --upgrade pipenv wheel
Collecting pipenv
  Downloading pipenv-2024.0.1-py3-none-any.whl.metadata (19 kB)
Collecting wheel
  Downloading wheel-0.43.0-py3-none-any.whl.metadata (2.2 kB)
Collecting certifi (from pipenv)
  Downloading certifi-2024.6.2-py3-none-any.whl.metadata (2.2 kB)
Collecting setuptools>=67 (from pipenv)
  Downloading setuptools-70.0.0-py3-none-any.whl.metadata (5.9 kB)
Collecting virtualenv>=20.24.2 (from pipenv)
  Downloading virtualenv-20.26.2-py3-none-any.whl.metadata (4.4 kB)
Collecting distlib<1,>=0.3.7 (from virtualenv>=20.24.2->pipenv)
  Downloading distlib-0.3.8-py2.py3-none-any.whl.metadata (5.1 kB)
Collecting filelock<4,>=3.12.2 (from virtualenv>=20.24.2->pipenv)
  Downloading filelock-3.15.0-py3-none-any.whl.metadata (2.8 kB)
Collecting platformdirs<5,>=3.9.1 (from virtualenv>=20.24.2->pipenv)
  Downloading platformdirs-4.2.2-py3-none-any.whl.metadata (11 kB)
Downloading pipenv-2024.0.1-py3-none-any.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 92.0 MB/s eta 0:00:00
Downloading wheel-0.43.0-py3-none-any.whl (65 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.8/65.8 kB 20.0 MB/s eta 0:00:00
Downloading setuptools-70.0.0-py3-none-any.whl (863 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 863.4/863.4 kB 87.3 MB/s eta 0:00:00
Downloading virtualenv-20.26.2-py3-none-any.whl (3.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 71.8 MB/s eta 0:00:00
Downloading certifi-2024.6.2-py3-none-any.whl (164 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 164.4/164.4 kB 43.7 MB/s eta 0:00:00
Downloading distlib-0.3.8-py2.py3-none-any.whl (468 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.9/468.9 kB 75.2 MB/s eta 0:00:00
Downloading filelock-3.15.0-py3-none-any.whl (15 kB)
Downloading platformdirs-4.2.2-py3-none-any.whl (18 kB)
Installing collected packages: distlib, wheel, setuptools, platformdirs, filelock, certifi, virtualenv, pipenv
  Attempting uninstall: setuptools
    Found existing installation: setuptools 58.1.0
    Uninstalling setuptools-58.1.0:
      Successfully uninstalled setuptools-58.1.0
Successfully installed certifi-2024.6.2 distlib-0.3.8 filelock-3.15.0 pipenv-2024.0.1 platformdirs-4.2.2 setuptools-70.0.0 virtualenv-20.26.2 wheel-0.43.0
Creating a virtualenv for this project...
Pipfile: /home/runner/work/opensearch-build/opensearch-build/Pipfile
Using /opt/hostedtoolcache/Python/3.9.19/x64/bin/python3.9 (3.9.19) to create virtualenv...
TypeError: object.__init__() takes exactly one argument (the instance to initialize)

Failed creating virtual environment
[pipenv.exceptions.VirtualenvCreationException]: Exception ignored in: <function BaseFileLock.__del__ at 0x7f743e116ee0>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/filelock/_api.py", line 365, in __del__
    self.release(force=True)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/virtualenv/util/lock.py", line 34, in release
    with self.thread_safe:
AttributeError: '_CountedFileLock' object has no attribute 'thread_safe'

Failed to create virtual environment.
Error: Process completed with exit code 1.
```

Thanks.

**Comment by peterzhuamazon** [comment]
Need to switch back to older version such as 3.9.12.

**Comment by peterzhuamazon** [comment]
Later might need to switch to other versions such as ubuntu-latest is changing.
See: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
And: https://github.com/actions/runner-images
