### ISSUE TITLE
[Build Break] K-NN similarity_search/CMakeLists.txt: No such file or directory

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#483]
**Describe the bug**
`sed: can't read external/nmslib/similarity_search/CMakeLists.txt: No such file or directory`

**To Reproduce**
1. `./bundle-workflow/build.sh manifests/opensearch-1.1.0.yml --component k-NN --snapshot`

```
+ cd jni
+ '[' x64 = x64 ']'
+ sed -i s/-march=native/-march=x86-64/g external/nmslib/similarity_search/CMakeLists.txt
sed: can't read external/nmslib/similarity_search/CMakeLists.txt: No such file or directory
2021-09-15 15:10:31 ERROR    Error building k-NN, retry with: /var/jenkins/workspace/bundle-build/bundle-workflow/build.sh manifests/opensearch-1.1.0.yml --component k-NN --snapshot
Traceback (most recent call last):
  File "/var/jenkins/workspace/bundle-build/bundle-workflow/src/build.py", line 63, in <module>
    builder.build(target)
  File "/var/jenkins/workspace/bundle-build/bundle-workflow/src/build_workflow/builder.py", line 38, in build
    self.git_repo.execute(build_command)
  File "/var/jenkins/workspace/bundle-build/bundle-workflow/src/git/git_repository.py", line 67, in execute
    subprocess.check_call(command, cwd=cwd, shell=True)
  File "/usr/lib64/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/var/jenkins/workspace/bundle-build/bundle-workflow/scripts/components/k-NN/build.sh -v 1.1.0 -a x64 -s true -o artifacts' returned non-zero exit status 2.
Jenkins 2.289.3

**Comment by jmazanec15** [comment]
Taking a look..

**Comment by jmazanec15** [comment]
"nmslib" submodule was not pulled before attempting to modify one of its files. [This](https://github.com/opendistro-for-elasticsearch/k-NN/blob/main/.github/workflows/CD.yml#L124-L127) didnt have to do it because the submodule was pulled when cmake had been implicitly ran on the machine via gradle before making this call.

I will explicitly init the submodule, test, and submit a new PR.

**Comment by dblock** [comment]
Closed via https://github.com/opensearch-project/opensearch-build/pull/489
