### ISSUE TITLE
[Bug]: The 

### ISSUE THREAD

**Issue by navneet1v** [opensearch-project/opensearch-build#5061]
### Describe the bug

The ref in the manifest is considered as a float rather than a string if branch name is 2.17.

Below are the logs I saw when I used 2.17 for a repo like Opensearch/k-NN:
```
✔ Successfully created virtual environment!
Virtualenv location: /home/ci-runner/.local/share/virtualenvs/opensearch-build-udCjdOuE
Installing dependencies from Pipfile.lock (6b098c)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Running ./src/run_build.py manifests/2.17.0/opensearch-2.17.0.yml --component OpenSearch k-NN -a arm64 --continue-on-error -d tar ...
Traceback (most recent call last):
  File "/home/ci-runner/opensearch-build/./src/run_build.py", line 113, in <module>
    sys.exit(main())
  File "/home/ci-runner/opensearch-build/./src/run_build.py", line 29, in main
    manifest = InputManifest.from_file(args.manifest)
  File "/home/ci-runner/opensearch-build/src/manifests/manifest.py", line 36, in from_file
    return loader(yml)
  File "/home/ci-runner/opensearch-build/src/manifests/input_manifest.py", line 113, in __init__
    super().__init__(data)
  File "/home/ci-runner/opensearch-build/src/manifests/component_manifest.py", line 31, in __init__
    super().__init__(data)
  File "/home/ci-runner/opensearch-build/src/manifests/manifest.py", line 112, in __init__
    self.validate(data)
  File "/home/ci-runner/opensearch-build/src/manifests/manifest.py", line 122, in validate
    raise ValueError(f"Invalid manifest schema: {v.errors}")
ValueError: Invalid manifest schema: {'components': [{4: ['no definitions validate', {'anyof definition 0': [{'ref': ['must be of string type']}], 'anyof definition 1': [{'dist': ['required field'], 'ref': ['unknown field'], 'repository': ['unknown field']}]}]}]}
```

### To reproduce

Setup the build containers and checkout the opensearch-build.

Now try to build the version let say 2.17 by changing the branch of the repo say k-NN to 2.17. 

run the command:

```
./build.sh manifests/2.17.0/opensearch-2.17.0.yml --component OpenSearch k-NN -a arm64 --continue-on-error -d tar
```

You will get the below error
```

✔ Successfully created virtual environment!
Virtualenv location: /home/ci-runner/.local/share/virtualenvs/opensearch-build-udCjdOuE
Installing dependencies from Pipfile.lock (6b098c)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Running ./src/run_build.py manifests/2.17.0/opensearch-2.17.0.yml --component OpenSearch k-NN -a arm64 --continue-on-error -d tar ...
Traceback (most recent call last):
  File "/home/ci-runner/opensearch-build/./src/run_build.py", line 113, in <module>
    sys.exit(main())
  File "/home/ci-runner/opensearch-build/./src/run_build.py", line 29, in main
    manifest = InputManifest.from_file(args.manifest)
  File "/home/ci-runner/opensearch-build/src/manifests/manifest.py", line 36, in from_file
    return loader(yml)
  File "/home/ci-runner/opensearch-build/src/manifests/input_manifest.py", line 113, in __init__
    super().__init__(data)
  File "/home/ci-runner/opensearch-build/src/manifests/component_manifest.py", line 31, in __init__
    super().__init__(data)
  File "/home/ci-runner/opensearch-build/src/manifests/manifest.py", line 112, in __init__
    self.validate(data)
  File "/home/ci-runner/opensearch-build/src/manifests/manifest.py", line 122, in validate
    raise ValueError(f"Invalid manifest schema: {v.errors}")
ValueError: Invalid manifest schema: {'components': [{4: ['no definitions validate', {'anyof definition 0': [{'ref': ['must be of string type']}], 'anyof definition 1': [{'dist': ['required field'], 'ref': ['unknown field'], 'repository': ['unknown field']}]}]}]}
```

### Expected behavior

The build should work. There should be no constraint on what is the branch name.

### Host / Environment

Docker image : opensearchstaging/ci-runner:ci-runner-al2-opensearch-build-v1 on the arm machine

### Additional context

I was trying to build my own distribution for testing some changes and then I encountered this issue.

### Relevant log output

```shell
Added already.
```

**Comment by prudhvigodithi** [comment]
@navneet1v here is an example https://github.com/opensearch-project/opensearch-build/pull/4873/files, we should use 
`ref: '2.17'`. 
Adding @peterzhuamazon @gaiksaya

**Comment by navneet1v** [comment]
Make sense. So I just need to add `''`. Thanks a lot. :)

**Comment by peterzhuamazon** [comment]
Close as yaml can treat non-quoted float value as float type.

Thanks.
