### ISSUE TITLE
[Bug]: OpenSearch-Dashboards distribution builds are failing for RPM assemble

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#5099]
### Describe the bug

See below build workflow runs:
* https://build.ci.opensearch.org/blue/organizations/jenkins/distribution-build-opensearch-dashboards/detail/distribution-build-opensearch-dashboards/7999/pipeline
* https://build.ci.opensearch.org/blue/organizations/jenkins/distribution-build-opensearch-dashboards/detail/distribution-build-opensearch-dashboards/7997/pipeline/793

Both workflows failed with below error:
```
Processing files: opensearch-dashboards-2.18.0-1.aarch64
error: File not found: /tmp/tmpns7bv2kd/BUILDROOT/opensearch-dashboards-2.18.0-1.aarch64/usr/share/opensearch-dashboards/.i18nrc.json

RPM build errors:
    File not found: /tmp/tmpns7bv2kd/BUILDROOT/opensearch-dashboards-2.18.0-1.aarch64/usr/share/opensearch-dashboards/.i18nrc.json
2024-10-10 02:27:03 INFO     Removing /tmp/tmpns7bv2kd
Traceback (most recent call last):
  File "/var/jenkins/workspace/distribution-build-opensearch-dashboards/./src/run_assemble.py", line 58, in <module>
    sys.exit(main())
  File "/var/jenkins/workspace/distribution-build-opensearch-dashboards/./src/run_assemble.py", line 49, in main
    bundle.package(output_dir)
  File "/var/jenkins/workspace/distribution-build-opensearch-dashboards/src/assemble_workflow/bundle.py", line 103, in package
    self.min_dist.build(self.bundle_recorder.package_name, dest)
  File "/var/jenkins/workspace/distribution-build-opensearch-dashboards/src/assemble_workflow/dist.py", line 85, in build
    self.__build__(name, dest)
  File "/var/jenkins/workspace/distribution-build-opensearch-dashboards/src/assemble_workflow/dist.py", line 136, in __build__
    BundleLinuxRpm(self.filename, self.path, self.min_path).build(name, dest, self.archive_path, self.build_cls)
  File "/var/jenkins/workspace/distribution-build-opensearch-dashboards/src/assemble_workflow/bundle_linux_rpm.py", line 95, in build
    subprocess.check_call(bundle_cmd, cwd=ext_dest, shell=True)
  File "/usr/lib64/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'rpmbuild -bb --define '_topdir /tmp/tmpns7bv2kd' --define '_version 2.18.0' --define '_architecture aarch64' opensearch-dashboards.rpm.spec' returned non-zero exit status 1.
script returned exit code 1
```

### To reproduce

Re-run above workflows or try building opensearch-dashboards RPM distribution from source. [Wiki](https://github.com/opensearch-project/opensearch-build/wiki/Building-an-OpenSearch-and-OpenSearch-Dashboards-Distribution)

### Expected behavior

Distribution builds should succeed.

**Comment by peterzhuamazon** [comment]
Seems like they remove the i18n plugins?
Would need to take a look as it is expecting the file there.

Thanks.

**Comment by peterzhuamazon** [comment]
This PR has moved the location of the i18n.json
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8414

**Comment by peterzhuamazon** [comment]
Issue identified, will PR tomorrow to fix this. Thanks.

**Comment by peterzhuamazon** [comment]
More related: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8424

**Comment by peterzhuamazon** [comment]
This file is not included in the final bundle anymore.

**Comment by peterzhuamazon** [comment]
PR:
* #5113
