### ISSUE TITLE
[Bundle Build Break] opensearch-job-scheduler-1.1.0.0.jar is invalid, missing -SNAPSHOT

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#510]
Change #502 the only new change for this build.

Run `bundle-workflow/build.sh manifests/opensearch-1.1.0.yml --component job-scheduler --snapshot`

See build failure:
```
2021-09-16 21:04:11 ERROR    Error building job-scheduler, retry with: /var/jenkins/workspace/bundle-build/bundle-workflow/build.sh manifests/opensearch-1.1.0.yml --component job-scheduler --snapshot
Traceback (most recent call last):
  File "/var/jenkins/workspace/bundle-build/bundle-workflow/src/build_workflow/build_artifact_check_maven.py", line 44, in check
    None,
  File "/var/jenkins/workspace/bundle-build/bundle-workflow/src/system/properties_file.py", line 57, in check_value_in
    raise PropertiesFile.UnexpectedKeyValuesError(key, expected, value)
system.properties_file.UnexpectedKeyValuesError: Expected to have Implementation-Version=any of ['1.1.0.0-SNAPSHOT', '1.1.0-SNAPSHOT', None], but was '1.1.0.0'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/jenkins/workspace/bundle-build/bundle-workflow/src/build.py", line 64, in <module>
    builder.export_artifacts()
  File "/var/jenkins/workspace/bundle-build/bundle-workflow/src/build_workflow/builder.py", line 48, in export_artifacts
    self.component_name, artifact_type, relative_path, absolute_path
  File "/var/jenkins/workspace/bundle-build/bundle-workflow/src/build_workflow/build_recorder.py", line 41, in record_artifact
    self.__check_artifact(artifact_type, artifact_file)
  File "/var/jenkins/workspace/bundle-build/bundle-workflow/src/build_workflow/build_recorder.py", line 61, in __check_artifact
    BuildArtifactCheckMaven(self.target).check(artifact_file)
  File "/var/jenkins/workspace/bundle-build/bundle-workflow/src/build_workflow/build_artifact_check_maven.py", line 48, in check
    raise BuildArtifactCheck.BuildArtifactInvalidError(path, str(e))
build_workflow.build_artifact_check.BuildArtifactInvalidError: Artifact opensearch-job-scheduler-1.1.0.0.jar is invalid. Expected to have Implementation-Version=any of ['1.1.0.0-SNAPSHOT', '1.1.0-SNAPSHOT', None], but was '1.1.0.0'.
```

**Comment by peternied** [comment]
Within the same worker, more than one job was being run, the integration tests are also adding content into the ~/.m2/... directory
![image](https://user-images.githubusercontent.com/2754967/133694467-c28cd817-1394-4f0f-915d-07aaaa0479db.png)

**Comment by dblock** [comment]
I am pretty sure this is caused by a polluted ~/.m2 for a previous run.

**Comment by peternied** [comment]
Next build passed, and mitigation is in place.
