### ISSUE TITLE
[BUG] BWC test suite does not run on Jenkins

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-build#536]
**Describe the bug**
BWC test job fails to run Jenkins due to misconfigured directory to kick off tests. 

```
Running ./bundle-workflow/src/run_bwc_test.py --s3-bucket <artifact_s3_bucket> --opensearch-version 1.1.0 --build-id 163 --architecture x64 --test-run-id 6 ...
2021-09-17 21:50:08 INFO     Switching to temporary work_dir: /tmp/tmp70l5b7_e
Traceback (most recent call last):
  File "/var/jenkins/workspace/bwc-test/bundle-workflow/src/run_bwc_test.py", line 31, in <module>
    sys.exit(main())
  File "/var/jenkins/workspace/bwc-test/bundle-workflow/src/run_bwc_test.py", line 26, in main
    args.s3_bucket, args.build_id, args.opensearch_version, args.architecture, cur_dir)
  File "/var/jenkins/workspace/bwc-test/bundle-workflow/src/manifests/bundle_manifest.py", line 85, in from_s3
    S3Bucket(bucket_name).download_file(manifest_s3_path, work_dir)
  File "/var/jenkins/workspace/bwc-test/bundle-workflow/src/aws/s3_bucket.py", line 99, in download_file
    local_dir = Path(dest)
  File "/usr/lib64/python3.7/pathlib.py", line 1027, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/lib64/python3.7/pathlib.py", line 674, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib64/python3.7/pathlib.py", line 658, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**To Reproduce**
Run `/bundle-workflow/src/test.sh bwc-test --s3-bucket <artifact_s3_bucket> --opensearch-version 1.1.0 --build-id 163 --architecture x64 --test-run-id 6`

**Comment by dblock** [comment]
Not that this is a problem here, but please change any calls to use `test.sh` to avoid any kind of dependency version issue.

**Comment by saratvemulapalli** [comment]
Haha good question. I actually cut the output from the Jenkins run to make it crisp but it was running it via `test.sh`.

```
/bundle-workflow/test.sh bwc-test --s3-bucket <artifact-bucket> --opensearch-version 1.1.0 --build-id 163 --architecture x64 --test-run-id 6
--s3-bucket <artifact-bucket> --opensearch-version 1.1.0 --build-id 163 --architecture x64 --test-run-id 6
Installing dependencies in ./bundle-workflow ...
Creating a virtualenv for this project...
Pipfile: /var/jenkins/workspace/bwc-test/bundle-workflow/Pipfile
Using /usr/bin/python3.7m (3.7.10) to create virtualenv...
created virtual environment CPython3.7.10.final.0-64 in 143ms
  creator CPython3Posix(dest=/home/ec2-user/.local/share/virtualenvs/bundle-workflow-WI5bCeIr, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/ec2-user/.local/share/virtualenv)
    added seed packages: pip==21.2.4, setuptools==58.0.4, wheel==0.37.0
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator


Successfully created virtual environment!
Virtualenv location: /home/ec2-user/.local/share/virtualenvs/bundle-workflow-WI5bCeIr
Installing dependencies from Pipfile.lock (22e2de)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Running ./bundle-workflow/src/run_bwc_test.py --s3-bucket artifact-bucket-stack-buildbucket-9omh0hnpg12q --opensearch-version 1.1.0 --build-id 163 --architecture x64 --test-run-id 6
```
