### ISSUE TITLE
[Bug]: OpenSearch Bundle Workflow couldn't build OpenSearch 1.0.0 and 1.0.1

### ISSUE THREAD

**Issue by xuezhou25** [opensearch-project/opensearch-build#568]
### Describe the bug

With the commit https://github.com/opensearch-project/opensearch-build/commit/1658890d407f55eb25d2cc904324470fb48d4ddd, the validation for build artifact version number is added.

The build of OpenSearch failed due to the version number mismatch.

For 1.0.0:
The manifest file uses "1.0" branch to build, 
https://github.com/opensearch-project/opensearch-build/blob/7765fd378ce5351ab60953ac5d1cd08e7d6c7300/manifests/1.0.0/opensearch-1.0.0.yml#L9
but "1.0" branch has bumped version to 1.0.1 (https://github.com/opensearch-project/OpenSearch/commit/1d59eafd7b2a2c178e3bc7d54f11cffefd1a0edc).

For 1.0.1:
The OpenSearch version actually doesn't change in bundle version 1.0.1, so it remains 1.0.0

### To reproduce

in `main` branch:
```
./bundle-workflow/build.sh manifests/1.0.0/opensearch-1.0.0.yml

./bundle-workflow/build.sh manifests/1.0.0/opensearch-1.0.1.yml
```

**Comment by dblock** [comment]
@xuezhou25 What was the error?

I believe this is a dup of https://github.com/opensearch-project/opensearch-build/issues/373

**Comment by xuezhou25** [comment]
Yes. The 1.0.1 is the same as #373.

For 1.0.0, I think it is due to `ref: "1.0"` in manifest file.
After run `./bundle-workflow/build.sh manifests/1.0.0/opensearch-1.0.0.yml`
error message:
```
2021-09-23 17:24:46 INFO     Recording maven artifact for OpenSearch: maven/org/opensearch/opensearch-x-content/maven-metadata.xml.md5 (from /tmp/tmpik2xj2mv/OpenSearch/artifacts/maven/org/opensearch/opensearch-x-content/maven-metadata.xml.md5)
2021-09-23 17:24:46 INFO     Recording maven artifact for OpenSearch: maven/org/opensearch/opensearch-x-content/maven-metadata.xml.sha256 (from /tmp/tmpik2xj2mv/OpenSearch/artifacts/maven/org/opensearch/opensearch-x-content/maven-metadata.xml.sha256)
2021-09-23 17:24:46 INFO     Recording maven artifact for OpenSearch: maven/org/opensearch/opensearch-x-content/maven-metadata.xml.sha512 (from /tmp/tmpik2xj2mv/OpenSearch/artifacts/maven/org/opensearch/opensearch-x-content/maven-metadata.xml.sha512)
2021-09-23 17:24:46 INFO     Recording maven artifact for OpenSearch: maven/org/opensearch/opensearch-x-content/maven-metadata.xml.sha1 (from /tmp/tmpik2xj2mv/OpenSearch/artifacts/maven/org/opensearch/opensearch-x-content/maven-metadata.xml.sha1)
2021-09-23 17:24:46 INFO     Recording maven artifact for OpenSearch: maven/org/opensearch/opensearch-x-content/maven-metadata.xml (from /tmp/tmpik2xj2mv/OpenSearch/artifacts/maven/org/opensearch/opensearch-x-content/maven-metadata.xml)
2021-09-23 17:24:46 INFO     Recording maven artifact for OpenSearch: maven/org/opensearch/opensearch-x-content/1.0.1/opensearch-x-content-1.0.1-sources.jar.sha256 (from /tmp/tmpik2xj2mv/OpenSearch/artifacts/maven/org/opensearch/opensearch-x-content/1.0.1/opensearch-x-content-1.0.1-sources.jar.sha256)
2021-09-23 17:24:46 INFO     Recording maven artifact for OpenSearch: maven/org/opensearch/opensearch-x-content/1.0.1/opensearch-x-content-1.0.1-javadoc.jar.sha256 (from /tmp/tmpik2xj2mv/OpenSearch/artifacts/maven/org/opensearch/opensearch-x-content/1.0.1/opensearch-x-content-1.0.1-javadoc.jar.sha256)
2021-09-23 17:24:46 INFO     Recording maven artifact for OpenSearch: maven/org/opensearch/opensearch-x-content/1.0.1/opensearch-x-content-1.0.1.jar.md5 (from /tmp/tmpik2xj2mv/OpenSearch/artifacts/maven/org/opensearch/opensearch-x-content/1.0.1/opensearch-x-content-1.0.1.jar.md5)
2021-09-23 17:24:46 INFO     Recording maven artifact for OpenSearch: maven/org/opensearch/opensearch-x-content/1.0.1/opensearch-x-content-1.0.1.pom.sha1 (from /tmp/tmpik2xj2mv/OpenSearch/artifacts/maven/org/opensearch/opensearch-x-content/1.0.1/opensearch-x-content-1.0.1.pom.sha1)
2021-09-23 17:24:46 INFO     Recording maven artifact for OpenSearch: maven/org/opensearch/opensearch-x-content/1.0.1/opensearch-x-content-1.0.1.pom.md5 (from /tmp/tmpik2xj2mv/OpenSearch/artifacts/maven/org/opensearch/opensearch-x-content/1.0.1/opensearch-x-content-1.0.1.pom.md5)
2021-09-23 17:24:46 INFO     Recording maven artifact for OpenSearch: maven/org/opensearch/opensearch-x-content/1.0.1/opensearch-x-content-1.0.1.module.md5 (from /tmp/tmpik2xj2mv/OpenSearch/artifacts/maven/org/opensearch/opensearch-x-content/1.0.1/opensearch-x-content-1.0.1.module.md5)
2021-09-23 17:24:46 INFO     Recording maven artifact for OpenSearch: maven/org/opensearch/opensearch-x-content/1.0.1/opensearch-x-content-1.0.1-sources.jar.sha512 (from /tmp/tmpik2xj2mv/OpenSearch/artifacts/maven/org/opensearch/opensearch-x-content/1.0.1/opensearch-x-content-1.0.1-sources.jar.sha512)
2021-09-23 17:24:46 INFO     Recording maven artifact for OpenSearch: maven/org/opensearch/opensearch-x-content/1.0.1/opensearch-x-content-1.0.1-sources.jar (from /tmp/tmpik2xj2mv/OpenSearch/artifacts/maven/org/opensearch/opensearch-x-content/1.0.1/opensearch-x-content-1.0.1-sources.jar)
2021-09-23 17:24:46 ERROR    Error building OpenSearch, retry with: ./bundle-workflow/build.sh manifests/1.0.0/opensearch-1.0.0.yml --component OpenSearch
Traceback (most recent call last):
  File "/home/ftianli/github/original/opensearch-build/bundle-workflow/src/build_workflow/build_artifact_check_maven.py", line 39, in check
    properties.check_value_in(
  File "/home/ftianli/github/original/opensearch-build/bundle-workflow/src/system/properties_file.py", line 57, in check_value_in
    raise PropertiesFile.UnexpectedKeyValuesError(key, expected, value)
system.properties_file.UnexpectedKeyValuesError: Expected to have Implementation-Version=any of ['1.0.0.0', '1.0.0', None], but was '1.0.1'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./bundle-workflow/src/build.py", line 64, in <module>
    builder.export_artifacts()
  File "/home/ftianli/github/original/opensearch-build/bundle-workflow/src/build_workflow/builder.py", line 47, in export_artifacts
    self.build_recorder.record_artifact(
  File "/home/ftianli/github/original/opensearch-build/bundle-workflow/src/build_workflow/build_recorder.py", line 41, in record_artifact
    self.__check_artifact(artifact_type, artifact_file)
  File "/home/ftianli/github/original/opensearch-build/bundle-workflow/src/build_workflow/build_recorder.py", line 61, in __check_artifact
    BuildArtifactCheckMaven(self.target).check(artifact_file)
  File "/home/ftianli/github/original/opensearch-build/bundle-workflow/src/build_workflow/build_artifact_check_maven.py", line 48, in check
    raise BuildArtifactCheck.BuildArtifactInvalidError(path, str(e))
build_workflow.build_artifact_check.BuildArtifactInvalidError: Artifact opensearch-x-content-1.0.1-sources.jar is invalid. Expected to have Implementation-Version=any of ['1.0.0.0', '1.0.0', None], but was '1.0.1'.
```

**Comment by dblock** [comment]
The "ref" is a branch name, not the actual version of the artifacts being built. The branch is fine. 

The [implementation of BuildArtifactCheckMaven](https://github.com/opensearch-project/opensearch-build/blob/999c97f4479f1d4ce0e206fe806707221567d775/bundle-workflow/src/build_workflow/build_artifact_check_maven.py#L43) requires the version to match exactly. When we release 1.0, everything is 1.0.0. But then for patch releases we allow that core is 1.0.0, while a plugin is 1.0.1. The fix is to improve the check that verifies that the version is not identical, but semantically correct, i.e for 1.0.x, any variation of 1.0.x+1 (+2, etc.) is acceptable.
