### ISSUE TITLE
[Bug]: OpenSearch Dashboards needs to rebuild core every time 

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#606]
### Describe the bug

OpenSearch dashboards requires to rebuild core every single time to build any of the components, which makes it very slow to debug component build problems.

### To reproduce

```sh
./build-workflow/build.sh manifests/1.1.0/openseach-dashboards-1.1.0.yml
```

Succeeds for all components.

```
./build-workflow/build.sh manifests/1.1.0/openseach-dashboards-1.1.0.yml --component=alertingDashboards
```

Fails with

```
+ PLUGIN_NAME=alertingDashboards
+ cp -r ../alertingDashboards/ ../OpenSearch-Dashboards/plugins
cp: cannot create directory '../OpenSearch-Dashboards/plugins': No such file or directory
2021-09-27 14:17:21 ERROR    Error building alertingDashboards, retry with: ./bundle-workflow/build.sh manifests/1.1.0/opensearch-dashboards-1.1.0.yml --component alertingDashboards
Traceback (most recent call last):
  File "./bundle-workflow/src/run_build.py", line 80, in <module>
    sys.exit(main())
  File "./bundle-workflow/src/run_build.py", line 66, in main
    builder.build(target)
  File "/home/ubuntu/source/opensearch-project/opensearch-build/dblock-opensearch-build/bundle-workflow/src/build_workflow/builder.py", line 41, in build
    self.git_repo.execute(build_command)
  File "/home/ubuntu/source/opensearch-project/opensearch-build/dblock-opensearch-build/bundle-workflow/src/git/git_repository.py", line 70, in execute
    subprocess.check_call(command, cwd=cwd, shell=True)
  File "/home/ubuntu/.pyenv/versions/3.7.11/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/home/ubuntu/source/opensearch-project/opensearch-build/dblock-opensearch-build/bundle-workflow/scripts/default/build.sh -v 1.1.0 -a x64 -s false -o artifacts -d true' returned non-zero exit status 1.

```

### Expected behavior

We could adopt something similar to how OpenSearch builds into `~/.m2` for dependencies with npm local, so that the output from the dashboards core could be published and preserved.

**Comment by kavilla** [comment]
We were thinking about to solve this issue we will allow for multiple components to be passed so it builds together

**Comment by peterzhuamazon** [comment]
#1278 provides a way to get it run.
We can try to use this for the fixes.

**Comment by gaiksaya** [comment]
One way might be to use [local-npm](https://www.npmjs.com/package/local-npm) (similar to maven local). Build dashboards and push to local-npm (one time) and then build the components on top of it.

**Comment by bbarani** [comment]
@kavilla @tianleh Is this still an open issue?

**Comment by peterzhuamazon** [comment]
Since we already implement the --component on both build and jenkins I think this can be closed.
Thanks.

**Comment by dblock** [comment]
This problem is about developers, not Jenkins, see above. I don't think it should be closed.

**Comment by bbarani** [comment]
@seanneumann @kavilla This needs to be prioritized to improve the build generation velocity. Can you please prioritize this as soon as possible?

**Comment by seanneumann** [comment]
Hey @bbarani. Taking a look with the team now.

**Comment by kavilla** [comment]
> @seanneumann @kavilla This needs to be prioritized to improve the build generation velocity. Can you please prioritize this as soon as possible?

Right now it does re-use the build from OpenSearch Dashboards in the default script:

* https://github.com/opensearch-project/opensearch-build/blob/main/scripts/default/opensearch-dashboards/build.sh#L88
* https://github.com/opensearch-project/opensearch-build/blob/main/scripts/components/ganttChartDashboards/build.sh

I don't think this will improve build generation velocity besides if we only just want to build a singular component which based on Peter's comment it is supported on Jenkins. Solving this would allow for developers locally  to push out if they wanted to build out `--component securityDashboards`.

Is there a case that this impacting @bbarani?

**Comment by bbarani** [comment]
@kavilla As far as I know, this is needed for granular build generation process work that is described [here](https://github.com/opensearch-project/opensearch-build/issues/1906). @peterzhuamazon, you mentioned that we can overcome this blocker by Bootstrapping the core, is that a long term solution?

**Comment by gaiksaya** [comment]
I found a couple of solutions in this article https://medium.com/@debshish.pal/publish-a-npm-package-locally-for-testing-9a00015eb9fd which can be used to publish opensearch-dashboards as a local npm package rather than bootstraping everytime (if I understand if correctly). Please take a look and see if this can be helpful. Also not sure if @Tengda-He is still working on this issue. If not please assign a new assignee. Removing the assignee for now.

Thanks!

**Comment by gaiksaya** [comment]
@kavilla @AMoo-Miki @ashwin-pc Wondering if you have any inputs for this issue?
Thanks!

**Comment by AMoo-Miki** [comment]
I am not sure I understand the problem enough or the historical context of this issue.
