### ISSUE TITLE
[Bug]: FileNotFoundError cleaning up after itself on Windows 

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#774]
### Describe the bug

```
2021-10-20 23:01:54 INFO     Created build manifest C:\Users\Administrator\source\opensearch-project\opensearch-build\dblock-opensearch-build\artifacts\manifest.yml
Traceback (most recent call last):
  File "./src/run_build.py", line 76, in <module>
  File "./src/run_build.py", line 70, in main
  File "C:\Users\Administrator\source\opensearch-project\opensearch-build\dblock-opensearch-build\src\system\temporary_directory.py", line 37, in __exit__
    shutil.rmtree(self.name, ignore_errors=False, onerror=g__handleRemoveReadonly)
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.7.9\lib\shutil.py", line 516, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.7.9\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.7.9\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.7.9\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 13 more times]
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.7.9\lib\shutil.py", line 400, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.7.9\lib\shutil.py", line 398, in _rmtree_unsafe
    os.unlink(fullname)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\tmp5u_7ibor\\OpenSearch\\benchmarks\\build\\generated\\sources\\annotationProcessor\\java\\main\\org\\opensearch\\benchmark\\search\\aggregations\\bucket\\terms\\generated\\LongKeyedBucketOrdsBenchmark_singleBucketIntoSingleImmutableBimorphicInvocation_jmhTest.java'
```

### To reproduce

On Windows

```
$ ./build.sh manifests/2.0.0/opensearch-2.0.0.yml --snapshot
```

completes, but throws the above error

**Comment by prudhvigodithi** [comment]
Hey @peterzhuamazon can you please add some details here, is this a known issue or is it already taken care ?

**Comment by peterzhuamazon** [comment]
Just close this one as all the changes are tracked in https://github.com/opensearch-project/opensearch-build/issues/2306
