### ISSUE TITLE
[bundle build dashboards]: Dashboard bundle build failed

### ISSUE THREAD

**Issue by abhinavGupta16** [opensearch-project/opensearch-build#839]
### Describe the bug

The bundle build for dashboards is failing because of `install.sh`

### To reproduce

Build the job on Jenkins to reproduce.

### Relevant log output

```shell
2021-10-29 20:23:17 INFO     Executing "bash /var/jenkins/workspace/bundle-build-dashboards/scripts/components/OpenSearch-Dashboards/install.sh -v 1.1.0 -p linux -a x64 -f /var/jenkins/workspace/bundle-build-dashboards/builds -o /tmp/tmp64v_m8z0/opensearch-dashboards-1.1.0-linux-x64" in /tmp/tmp64v_m8z0/opensearch-dashboards-1.1.0-linux-x64
+ getopts :ha:o: arg
+ case $arg in
+ echo 'Invalid option: -?'
Invlid option: -?
+ ext 1
Traceback (most recent call last):
  ​File "./sc/run_assemble.py", lin 50, in <module>
    ​sys.exit(main())
  ​File "./src/run_assemble.py", line 36, in main
    ​bundle.install_min()
 ​File "/var/jenkins/workspace/budle-build-dashboards/src/assemble_workflow/bundle.py", line 65, in install_min
    ​self._execute(install_command
  ​File "/var/jenkins/workspace/bundle-build-dashboards/src/assemble_workflo/bundle.py", line 101, in _execute
    ​subprocess.check_call(command, cwd=elf.min_dist.archive_path, shell=True)
  ​File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
    ​raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'bash /var/jenkins/workspace/bundle-build-dashboards/scripts/components/OpenSearch-Dashboards/install.sh -v 1.1.0 -p linux -a x64 -f /var/jenkins/workspace/bundle-build-dashboards/builds -o /tmp/tmp64v_m8z0/opensearch-dashbo10-linux-x64' returned non-zero exit status 1.
```
```

**Comment by abhinavGupta16** [comment]
@dblock Can you have a look at the build break? It maybe related to the changes in the install script. Thank you!
