### ISSUE TITLE
[Bundle Build Break]: PerformanceAnalyzer build failure

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/opensearch-build#885]
### Describe the bug

Bundle build workflow on Jenkins is broken after #871 is merged. 
Here is the error context: 
```
> Task :updateShas FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':updateShas'.
> Could not resolve all files for configuration ':runtimeClasspath'.
   > Could not find org.opensearch:performanceanalyzer-rca:1.2.0.0.
     Searched in the following locations:
       - https://jcenter.bintray.com/org/opensearch/performanceanalyzer-rca/1.2.0.0/performanceanalyzer-rca-1.2.0.0.pom
       - https://repo.maven.apache.org/maven2/org/opensearch/performanceanalyzer-rca/1.2.0.0/performanceanalyzer-rca-1.2.0.0.pom
       - file:/usr/share/opensearch/.m2/repository/org/opensearch/performanceanalyzer-rca/1.2.0.0/performanceanalyzer-rca-1.2.0.0.pom
       - https://plugins.gradle.org/m2/org/opensearch/performanceanalyzer-rca/1.2.0.0/performanceanalyzer-rca-1.2.0.0.pom
       - https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/performanceanalyzer-rca/1.2.0.0/performanceanalyzer-rca-1.2.0.0.pom
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

### To reproduce

run `./build.sh manifests/1.2.0/opensearch-1.2.0.yml --component performance-analyzer`

**Comment by zelinh** [comment]
Could you take a look at this build failure? @kjoseph07

**Comment by kjoseph07** [comment]
> Could you take a look at this build failure? @kjoseph07

Taking a look now.

**Comment by peternied** [comment]
After the PR seeing another kind of failure:
```
-> Installed opensearch-performance-analyzer with folder name opensearch-performance-analyzer
2021-11-04 20:05:58 INFO     Executing "bash /var/jenkins/workspace/bundle-build/scripts/components/performance-analyzer/install.sh -v 1.2.0 -p linux -a x64 -f /var/jenkins/workspace/bundle-build/builds -o /tmp/tmp7ervwsrj/opensearch-1.2.0" in /tmp/tmp7ervwsrj/opensearch-1.2.0
+ getopts :h:a:o: arg
+ case $arg in
+ echo 'Invalid option: -?'
Invalid option: -?
+ exit 1
Traceback (most recent call last):
  File "./src/run_assemble.py", line 50, in <module>
    sys.exit(main())
  File "./src/run_assemble.py", line 37, in main
    bundle.install_plugins()
  File "/var/jenkins/workspace/bundle-build/src/assemble_workflow/bundle.py", line 70, in install_plugins
    self.install_plugin(plugin)
  File "/var/jenkins/workspace/bundle-build/src/assemble_workflow/bundle_opensearch.py", line 22, in install_plugin
    super().install_plugin(plugin)
  File "/var/jenkins/workspace/bundle-build/src/assemble_workflow/bundle.py", line 94, in install_plugin
    self._execute(install_command)
  File "/var/jenkins/workspace/bundle-build/src/assemble_workflow/bundle.py", line 101, in _execute
    subprocess.check_call(command, cwd=self.min_dist.archive_path, shell=True)
  File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'bash /var/jenkins/workspace/bundle-build/scripts/components/performance-analyzer/install.sh -v 1.2.0 -p linux -a x64 -f /var/jenkins/workspace/bundle-build/builds -o /tmp/tmp7ervwsrj/opensea
```

**Comment by dblock** [comment]
There's a custom install.sh that hasn't updated its args. Copy from https://github.com/opensearch-project/opensearch-build/blob/main/scripts/default/install.sh

**Comment by zelinh** [comment]
That performance-analyzer install.sh has been updated as part of #878. 
Bundle build works now. Closing this issue.
