### ISSUE TITLE
[Bug]: OpenSearch dist `opensearch-tar-install.sh` does not work

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/opensearch-build#917]
### Describe the bug

Not sure if it's just my local environment setup. Seems like I have to set an environment variable.

When trying to run `opensearch-tar-install.sh` I get the following message:

```
OpenSearch Security Demo Installer
 ** Warning: Do not use on production or public reachable systems **
Basedir: /home/ubuntu/releases/opensearch-1.2.0
OpenSearch install type: .tar.gz on DISTRIB_ID=Ubuntu
OpenSearch config dir: /home/ubuntu/releases/opensearch-1.2.0/config
OpenSearch config file: /home/ubuntu/releases/opensearch-1.2.0/config/opensearch.yml
OpenSearch bin dir: /home/ubuntu/releases/opensearch-1.2.0/bin
OpenSearch plugins dir: /home/ubuntu/releases/opensearch-1.2.0/plugins
OpenSearch lib dir: /home/ubuntu/releases/opensearch-1.2.0/lib
Detected OpenSearch Version: x-content-1.2.0
Detected OpenSearch Security Version: 1.2.0.0
/home/ubuntu/releases/opensearch-1.2.0/config/opensearch.yml seems to be already configured for Security. Quit.
done security
done plugins
Checking kNN library
TEST FAILED OR FILE NOT EXIST /home/ubuntu/releases/opensearch-1.2.0/plugins/opensearch-knn/knnlib/libKNNIndexV2_0_11.so
/home/ubuntu/releases/opensearch-1.2.0/plugins/opensearch-knn/knnlib/libopensearchknn_common.so
/home/ubuntu/releases/opensearch-1.2.0/plugins/opensearch-knn/knnlib/libopensearchknn_faiss.so
/home/ubuntu/releases/opensearch-1.2.0/plugins/opensearch-knn/knnlib/libopensearchknn_nmslib.so
KNN lib path not found, set new path
:/home/ubuntu/releases/opensearch-1.2.0/plugins/opensearch-knn/knnlib
Exception in thread "main" java.lang.NoSuchFieldError: LUCENE_8_10_1
        at org.opensearch.Version.<clinit>(Version.java:77)
        at org.opensearch.bootstrap.Bootstrap.<init>(Bootstrap.java:98)
        at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:366)
        at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:178)
        at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:169)
        at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100)
        at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
        at org.opensearch.cli.Command.main(Command.java:101)
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:135)
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:101)
```

Looks like file was renamed or removed.

### To reproduce

* `wget -c https://ci.opensearch.org/ci/dbc/bundle-build/1.2.0/941/linux/x64/dist/opensearch-1.2.0-linux-x64.tar.gz -O - | tar -xz`
* `./opensearch-1.2.0/opensearch-tar-install.sh`

### Expected behavior

`.opensearch-tar-install.sh` to work and setup my cluster.

### Screenshots

n/a

### Host / Environment

Ubuntu

### Additional context

The assemble workflow takes this exact script:
https://github.com/opensearch-project/opensearch-build/blob/main/scripts/legacy/tar/linux/opensearch-tar-install.sh

and adds it to the `dist` folder. If there is updates required the linked script should be updated.

### Relevant log output

```shell
Checking kNN library
TEST FAILED OR FILE NOT EXIST /home/ubuntu/releases/opensearch-1.2.0/plugins/opensearch-knn/knnlib/libKNNIndexV2_0_11.so
/home/ubuntu/releases/opensearch-1.2.0/plugins/opensearch-knn/knnlib/libopensearchknn_common.so
/home/ubuntu/releases/opensearch-1.2.0/plugins/opensearch-knn/knnlib/libopensearchknn_faiss.so
/home/ubuntu/releases/opensearch-1.2.0/plugins/opensearch-knn/knnlib/libopensearchknn_nmslib.so
KNN lib path not found, set new path
:/home/ubuntu/releases/opensearch-1.2.0/plugins/opensearch-knn/knnlib
Exception in thread "main" java.lang.NoSuchFieldError: LUCENE_8_10_1
        at org.opensearch.Version.<clinit>(Version.java:77)
        at org.opensearch.bootstrap.Bootstrap.<init>(Bootstrap.java:98)
        at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:366)
        at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:178)
        at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:169)
        at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100)
        at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
        at org.opensearch.cli.Command.main(Command.java:101)
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:135)
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:101)
```

**Comment by kavilla** [comment]
@ jmazanec15 would you have some insight on this one?

**Comment by jmazanec15** [comment]
This bug looks like its coming from OpenSearch boot and not k-NN.

**Comment by jmazanec15** [comment]
#923 cleans up some of the messages around installation wrt k-NN.

**Comment by kavilla** [comment]
Working for me on latest build for OpenSearch. Yeah I guess the cleaning log messages will up.

**Comment by gaiksaya** [comment]
Closing this issue as it is resolved. @kavilla please reopen if you need to. Thanks!
