### ISSUE TITLE
[BundleBuild Break] OpenSearch Could not resolve commons-codec:commons-codec:1.13.

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#919]
```
* What went wrong:
Execution failed for task ':buildSrc:compileJava'.
> Could not resolve all files for configuration ':buildSrc:compileClasspath'.
   > Could not resolve commons-codec:commons-codec:1.13.
     Required by:
         project :buildSrc
      > Could not resolve commons-codec:commons-codec:1.13.
         > Could not get resource 'https://jcenter.bintray.com/commons-codec/commons-codec/1.13/commons-codec-1.13.pom'.
            > Could not GET 'https://jcenter.bintray.com/commons-codec/commons-codec/1.13/commons-codec-1.13.pom'.
               > PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
   > Could not resolve org.apache.commons:commons-compress:1.21.
     Required by:
         project :buildSrc
....

BUILD FAILED in 11s
2021-11-09 13:02:44 ERROR    Error building OpenSearch, retry with: ./build.sh manifests/1.2.0/opensearch-1.2.0.yml --component OpenSearch --snapshot
Traceback (most recent call last):
  File "./src/run_build.py", line 65, in <module>
    sys.exit(main())
  File "./src/run_build.py", line 53, in main
    builder.build(build_recorder)
  File "/var/jenkins/workspace/bundle-build/src/build_workflow/builder_from_source.py", line 49, in build
    self.git_repo.execute(build_command)
  File "/var/jenkins/workspace/bundle-build/src/git/git_repository.py", line 77, in execute
    subprocess.check_call(command, cwd=cwd, shell=True)
  File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'bash /var/jenkins/workspace/bundle-build/scripts/components/OpenSearch/build.sh -v 1.2.0 -p linux -a x64 -s true -o builds' returned non-zero exit status 1.
```

**Comment by peternied** [comment]
After reviewing with @gaiksaya this looks like a random certificate issue on `jcenter.bintray.com`
