### ISSUE TITLE
[Bug]: Add check for backslash for CI public endpoint when running ./test.sh integ-test

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-build#969]
### Describe the bug

When a backslash exists in the CI public endpoint, e.g
`./test.sh integ-test https://ci.opensearch.org/ci/dbc/bundle-build/1.2.0/998/linux/x64/`

an extra backslash is appended to the metadata url leading to download error. 

`Downloading https://ci.opensearch.org/ci/dbc/bundle-build/1.2.0/998/linux/x64//builds/maven/org/opensearch/client/test/test/maven-metadata.xml`

Below is the complete error log.

```
Installing dependencies in . ...
Installing dependencies from Pipfile.lock (c3492c)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Running ./src/run_integ_test.py https://ci.opensearch.org/ci/dbc/bundle-build/1.2.0/998/linux/x64/ ...
2021-11-16 19:36:53 INFO     Loading ./src/test_workflow/config/test_manifest.yml
2021-11-16 19:36:53 INFO     Loading https://ci.opensearch.org/ci/dbc/bundle-build/1.2.0/998/linux/x64/dist/manifest.yml
2021-11-16 19:36:53 INFO     Loading https://ci.opensearch.org/ci/dbc/bundle-build/1.2.0/998/linux/x64/builds/manifest.yml
2021-11-16 19:36:54 INFO     TestRecorder recording logs in /usr/share/opensearch/workspace/opensearch-build/test-results/603404e77ba44d36a7b5e4372a5a27de/integ-test
2021-11-16 19:36:54 INFO     Downloading to /usr/share/opensearch/.m2/repository ...
2021-11-16 19:36:54 INFO     Downloading https://ci.opensearch.org/ci/dbc/bundle-build/1.2.0/998/linux/x64//builds/maven/org/opensearch/client/test/test/maven-metadata.xml into /usr/share/opensearch/.m2/repository/org/opensearch/client/test/test/maven-metadata.xml ...
Traceback (most recent call last):
  File "./src/run_integ_test.py", line 65, in <module>
    sys.exit(main())
  File "./src/run_integ_test.py", line 36, in main
    dependency_installer.install_maven_dependencies()
  File "/usr/share/opensearch/workspace/opensearch-build/src/test_workflow/dependency_installer.py", line 33, in install_maven_dependencies
    self.download(maven_artifacts, "builds", self.maven_local_path)
  File "/usr/share/opensearch/workspace/opensearch-build/src/test_workflow/dependency_installer.py", line 59, in download
    self.__download_or_copy(url, local_path)
  File "/usr/share/opensearch/workspace/opensearch-build/src/test_workflow/dependency_installer.py", line 66, in __download_or_copy
    urllib.request.urlretrieve(source, dest)
  File "/usr/lib64/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib64/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib64/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

### To reproduce

` ./test.sh integ-test https://ci.opensearch.org/ci/dbc/bundle-build/1.2.0/998/linux/x64/` with a backslash in the end

The head of the commit is `ac0082cc30399b20d787352a00f589797ebc8c02`

### Expected behavior

The metadata xml shall be successfully downloaded similar to manifest xml.

**Comment by gaiksaya** [comment]
[Triage] Need better error handling.

**Comment by dblock** [comment]
This needs to combine URLs better and handle the `/` at the end of the input URL.

**Comment by rishabh6788** [comment]
This issue no longer exists. Ran the the integ-test with below params and found no issue. 
```
./test.sh integ-test manifests/2.4.1/opensearch-2.4.1-test.yml --component ml-commons --test-run-id 3455 --paths opensearch=https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.4.1/6667/linux/arm64/tar/
```
and
```
./test.sh integ-test manifests/2.4.1/opensearch-2.4.1-test.yml --component ml-commons --test-run-id 3455 --paths opensearch=https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.4.1/6667/linux/arm64/tar
```
@gaiksaya please confirm if this can be closed.

**Comment by zelinh** [comment]
I'm still seeing this issue with command `./test.sh integ-test manifests/2.4.1/opensearch-2.4.1-test.yml --component anomaly-detection --paths opensearch=https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.4.1/6667/linux/x64/tar/`

```
2023-01-03 22:52:33 INFO     Downloading https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.4.1/6667/linux/x64/tar//builds/opensearch/plugins/opensearch-job-scheduler-2.4.1.0.zip into /tmp/tmpnsl2vrus/anomaly-detection/src/test/resources/job-scheduler/opensearch-job-scheduler-2.4.1.0.zip ...
2023-01-03 22:52:33 INFO     Removing /tmp/tmpnsl2vrus
Traceback (most recent call last):
  File "./src/run_integ_test.py", line 36, in <module>
    sys.exit(main())
  File "./src/run_integ_test.py", line 25, in main
    all_results = IntegTestRunners.from_test_manifest(args, test_manifest).run()
  File "/usr/share/opensearch/opensearch-build/src/test_workflow/integ_test/integ_test_runner.py", line 47, in run
    test_results = test_suite.execute_tests()
  File "/usr/share/opensearch/opensearch-build/src/test_workflow/integ_test/integ_test_suite_opensearch.py", line 49, in execute_tests
    self.__install_build_dependencies()
  File "/usr/share/opensearch/opensearch-build/src/test_workflow/integ_test/integ_test_suite_opensearch.py", line 59, in __install_build_dependencies
    self.__copy_job_scheduler_artifact()
  File "/usr/share/opensearch/opensearch-build/src/test_workflow/integ_test/integ_test_suite_opensearch.py", line 68, in __copy_job_scheduler_artifact
    self.dependency_installer.install_build_dependencies({"opensearch-job-scheduler": job_scheduler.version}, custom_local_path)
  File "/usr/share/opensearch/opensearch-build/src/test_workflow/dependency_installer_opensearch.py", line 42, in install_build_dependencies
    self.download_or_copy(path, local_path)
  File "/usr/share/opensearch/opensearch-build/src/test_workflow/dependency_installer.py", line 64, in download_or_copy
    urllib.request.urlretrieve(source_url, dest)
  File "/usr/local/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

I also run with the commands @rishabh6788 posted above and they are passing. After some investigation, the reason I think is the integ test run on `ml-common` doesn't have any `build-dependencies` according to the test manifest, which actually causes the issue. I will be looking into a path fix.

**Comment by zelinh** [comment]
Closing this issue as it's fixed.
